A better page on SPREE
w3f/polkadot-wiki pull request #110
Opened 2019-10-24 12:00 UTC by lsaether

2019-10-25 10:12 UTC, Swader requested changes
Much clearer. I would also clarify storage a bit more, and name some more examples of SPREE modules. For example, if a SPREE module has shared storage for all the parachains, that means state bloat. How does this affect validators - do all validators need to maintain all the SPREE modules, or do they only maintain those into which the parachains they are devoted to have opted into? Likewise, is there a concept of pruning / state rent in SPREE? If we have a balance SPREE module, then:

a) Where can one inspect the history of transactions affecting that SPREE module, i.e. will the current polkadot explorer support this and
b) When it grows too much, can the relay chain somehow shed this history if it's not needed? And to that effect, will all SPREE modules be permanent storage, or can some of them be transient too with "pure" functions or temporary payloads only?

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +executed on destination parachains. While ICMP guarentees the delivery of a message, it does not guarentee what code
```suggestion
executed on destination parachains. While ICMP guarantees the delivery of a message, it does not guarantee what code
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +passing, SPREE is the trustless interpration of the message and a key part to the usefulness of ICMP.
```suggestion
passing, SPREE is the trustless interpenetration of the message and a key part to the usefulness of ICMP.
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +SPREE modules are like recipes in cookbooks. For example, if we give an order to a cook to make a souffle, and we’re
```suggestion
SPREE modules are like recipes in cookbooks. For example, if we give an order to a cook to make a soufflé, and we’re
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +will be made. However, let’s say that a cook has the “Souffle Maker’s Manual” on their bookshelf and has committed
```suggestion
will be made. However, let’s say that a cook has the “Soufflé Maker’s Manual” on their bookshelf and has committed
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +precise understanding of what will happen when we tell the cook to make a souffle. In this example, “make a souffle” was
```suggestion
precise understanding of what will happen when we tell the cook to make a soufflé. In this example, “make a soufflé” was
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +In concrete terms, SPREE modules could be useful for various functionally on Polkadot. One suggested use case of SPREE
```suggestion
In concrete terms, SPREE modules could be useful for various functionality on Polkadot. One suggested use case of SPREE
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +other parachain would have to be trusted. Having shared code which exist in appendices that the parachain can opt-in to
```suggestion
other parachain would have to be trusted. Having shared code which exists in appendices that the parachain can opt-in to
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +supporting resolves the need for trust and makes the execution of the appendices completely trustless.
```suggestion
resolves the need for trust and makes the execution of the appendices completely trustless.
```

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +supporting resolves the need for trust and makes the execution of the appendices completely trustless.
Resolves the need for trust + makes ... completely trustless = unnecessary repetition?

2019-10-25 10:12 UTC, Swader commented on docs/learn-spree.md
> +On 28 March, 2019 u/Tawaren, a member of the Polkadot community, made a post on [r/dot](polkadot reddit) called
```suggestion
On 28 March, 2019 u/Tawaren, a member of the Polkadot community, made a post on [r/dot][polkadot reddit] called
```

2019-10-28 14:31 UTC, lsaether commented
SPREE modules shouldn't be shared storage for all parachains, but one storage root for each instance created for each parachain that opts into it. 

Forseeably the only storage that needs to be kept on the relaychain would be parachains * SPREE modules bits for whether or not a particular parachain opts into a particular SPREE module. And then a storage root for this SPREE module, but it could be possible to use a single SPREE storage root per parachain. Collators would be expected to keep data, so validators wouldn't need to do any extra work besides their normal validation duties against the SPREE module now too.

a) Yes.
b) Probably there's some limit of SPREE modules that can be active at any one time and some of them would be replaced by new ones over time. Is that what you mean by transient or with temporary payloads?

2019-10-29 06:22 UTC, ansonla3 commented
would it be better to have a diagram to explain the whole operation (like run through an example) to give the readers to have a better understanding in general?

2019-10-31 13:50 UTC, Swader commented
Yes, that's what I meant, being able to reliably get rid of past implementations.

@ansonla3 I like that idea. I think SPREE are going to be a big selling point that needs to be clarified, so going more in depth would be great.

2019-11-05 09:31 UTC, lsaether commented
We can go more in-depth on a subsequent PR but I think already this page is an improvement. Can you re-review @Swader ?

2019-11-05 09:47 UTC, Swader approved these changes

2019-11-05 09:48 UTC, merged

2019-11-12 10:12 UTC, FatemeShirazi approved these changes
I think it looks ok, but since it is not implemented yet we should indicate at the beginning of the page that this is only a tentative plan and details might change.

2019-11-12 11:17 UTC, lsaether commented
Thanks @FatemeShirazi will update that!