Update research.md
w3f/polkadot-wiki pull request #1145
Opened 2020-10-13 14:52 UTC by MajellaH

Fixes #1144 -update research papers and research blogs, correct typo
Needs sidebars added to new articles

2020-10-13 14:57 UTC, Swader requested changes
Formatting

2020-10-13 14:57 UTC, Swader commented on docs/research.md
> +## Research Blogs
You need to make these list items, so start every line with a dash or asterisk. If you look at the preview of this file, you'll notice they're not rendered as a list, but inline one after the other.

2020-10-13 16:11 UTC, MajellaH commented on docs/research.md
> +## Research Blogs
Done. Thanks...

2020-10-14 06:42 UTC, lsaether approved these changes

2020-10-14 09:37 UTC, merged