Adding guide for democracy
w3f/polkadot-wiki pull request #142
Opened 2019-11-06 20:20 UTC by lsaether

closes #132

2020-02-11 14:00 UTC, laboon commented
@lsaether Is this still a draft?  Is it something that can be merged or merged after a bit of work?

2020-02-19 14:52 UTC, lsaether commented
Not ready for review, just checking for conflicts.

2020-02-20 10:56 UTC, lsaether commented
Ready for review.

2020-02-20 17:24 UTC, Swader requested changes
Nitpicks and typos, some clarifications needed.

Should we add disclaimers to pages that use Polkadot JS UI that the UI is only one of many possible implementations and that things might change in the future? Seems a bit vendor-lock-iny to constantly recommend a hosted UI without at least encouraging people to run it locally.

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +as its instantiated in Polkadot and Kusama. The other two bodies are the
```suggestion
as it's instantiated in Polkadot and Kusama. The other two bodies are the
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +This guide will instruct token holders how to proposed and vote on public
```suggestion
This guide will instruct token holders how to propose and vote on public
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +You can copy this preimage hash and save it for the next step.
```suggestion
You can copy this preimage hash and save it for the next step. There is no need to click Submit Preimage at this point, though you could. We'll go over that in the next section.
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +the actual preimage for this proposal. The next step you will submit the preimage.
```suggestion
the actual preimage for this proposal. In the next step you will submit the preimage.
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +proposal will be tabled as a referendum to be voted on every launch period.
```suggestion
proposal - in value, not number of supporters - will be tabled as a referendum to be voted on every launch period.
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +You may also lock up your tokens for a greater length of time to weigh your vote
Clarify what it means to lock tokens in this context - what can the locked tokens still do? Can they be double-locked for, e.g. identity, or council votes?

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +To vote on a referendum, navigate to the "Democracy" tab of Polkadot Apps. Any
```suggestion
To vote on a referendum, navigate to the ["Democracy" tab of Polkadot Apps](https://polkadot.js.org/apps/#/democracy/). Any
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +you hold, while the maximum lock up of 128 days means you can make your vote count
Maximum is 6x at 256 days.

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +You will see an output similar to below, showing the addresses which you have
```suggestion
You will see an output similar to below, showing the addresses to which you have
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +you must simply send the `undelegate` transaction from the account you wish to
```suggestion
you must send the `undelegate` transaction from the account you wish to
```

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +"Submit transaction" and confirm.
Explain what happens to locked tokens in this case.

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +that your vote will be locked longer. So choose wisely!
Are you locking tokens in the delegation, or to a specific decision that someone else voted for? I.e. if Alice votes YES on Proposal 1, and you delegate 20 tokens at 6x conviction, does this mean Alice's vote on Proposal 1 gets +120 immediately, or does she get the 120 to vote with on another referendum down the line? Which one? How do you decide what she can use those on?

2020-02-20 17:24 UTC, Swader commented on docs/maintain-guides-democracy.md
> +Setting a proxy is simple and involves only submitting a single transaction,
```suggestion
Setting a proxy involves submitting a single transaction, 
```

2020-02-25 12:57 UTC, Swader requested changes
I'd like some more clarifications added to some parts. Also some nitpicks about spelling out numbers below 10 as per "standards".

2020-02-25 12:57 UTC, Swader commented on docs/maintain-guides-democracy.md
> +of each other, so a 8 week lock does not become a 15 week lock if you vote again
```suggestion
of each other, so an eight week lock does not become a 15 week lock if you vote again
```

2020-02-25 12:57 UTC, Swader commented on docs/maintain-guides-democracy.md
> +a week later, rather another 8 week lock is placed to extend the lock just 1 extra
```suggestion
a week later, rather another eight week lock is placed to extend the lock just one extra
```

2020-02-25 12:57 UTC, Swader commented on docs/maintain-guides-democracy.md
> +"Submit transaction" and confirm.
No explanation about this?

2020-02-25 12:57 UTC, Swader commented on docs/maintain-guides-democracy.md
> +that your vote will be locked longer. So choose wisely!
I think this should still be clarified.

2020-02-27 09:16 UTC, lsaether commented
@Swader Can you review again? I think the points you wanted clarified have been resolved.

2020-02-27 11:13 UTC, Swader approved these changes
Perfect, this was a huge missing piece, I had no idea about this!

2020-02-27 11:39 UTC, merged