Add section on finding errors from polkascan and subscan
w3f/polkadot-wiki pull request #1425
Opened 2020-12-10 11:24 UTC by lsaether

closes #1415

2020-12-10 12:53 UTC, laboon requested changes
Looks like you looked up the error for Balances but then references Timestamps (maybe swapped `error` and `index`).  Also added some clarifications.

2020-12-10 12:53 UTC, laboon commented on docs/maintain-errors.md
> +Polkascan and Subscan show the `ExtrnsicFailed` event when a transaction does not succeed
```suggestion
Polkascan and Subscan show the `ExtrinsicFailed` event when a transaction does not succeed
```

2020-12-10 12:53 UTC, laboon commented on docs/maintain-errors.md
> +For example, if we have `index` is 5 and `index` is 3 like in the example linked above, we need to
```suggestion
For example, if `index` is 5 and `error` is 3, as in the example linked above, we need to
```

2020-12-10 12:53 UTC, laboon commented on docs/maintain-errors.md
> +look at the runtime for the 4th error in the pallet at index 5.
```suggestion
look at the runtime for the fourth error (index 3) in the sixth pallet (index 5).
```

2020-12-10 12:53 UTC, laboon commented on docs/maintain-errors.md
> +we see that the pallet at index 3 is "Timestamp". Now we will check the timestamp pallet's code
```suggestion
we see that the pallet at index 5 is "Balances". Now we will check the Balances pallet's code
```

2020-12-10 12:53 UTC, laboon commented on docs/maintain-errors.md
> +which is hosted in the Substrate repository. According to
```suggestion
which is hosted in the Substrate repository, and look for the fourth error in the Error enum. According to
```

2020-12-17 11:18 UTC, lsaether commented
Thanks!

2020-12-17 11:37 UTC, laboon approved these changes

2020-12-17 11:38 UTC, merged