Update learn-nominator.md
w3f/polkadot-wiki pull request #1663
Opened 2021-02-03 06:52 UTC by rskntroot

Add a section regarding minimum required DOT for staking.

2021-02-03 18:39 UTC, Swader requested changes
We don't want to be specific with any numbers because they change too frequently.

2021-02-03 18:39 UTC, Swader commented on docs/learn-nominator.md
> +
```suggestion
### Required Minimum Stake

Due to the overwhelming demand and the way the algorithm optimizes the nominator set,
there is a minimum number of DOT you must nominate with in order to be effective.

This number fluctuates day by day, and the most recent and up to date version can be
found out using [this community-developed tool](https://polkaview.network/dot) or
through [these scripts](https://github.com/w3f/validator-stats) which you can run on your machine.

```

2021-02-03 20:20 UTC, rskntroot commented
> We don't want to be specific with any numbers because they change too frequently.

Was not aware of the tool, appreciate the changes.

2021-02-03 20:23 UTC, Swader commented
@laboon I am linking here to a community made tool. It's very practical and in my opinion safe to link to, but wanted to know if you had a different opinion.

2021-02-04 11:53 UTC, laboon commented
I think if it's OK if we note that it is a community-generated tools. But I want to change the wording on this.

2021-02-04 11:59 UTC, laboon requested changes

2021-02-04 11:59 UTC, laboon commented on docs/learn-nominator.md
> +Due to the overwhelming demand and the way the algorithm optimizes the nominator set,
```suggestion
Due to the way the [Phragmen algorithm](learn-phragmen) generates the solution set,
and due to the fact that the solution set must fit in a single block, 
```

2021-02-04 11:59 UTC, laboon commented on docs/learn-nominator.md
> +there is a minimum number of DOT you must nominate with in order to be effective.
```suggestion
there is a minimum number of DOT you must nominate with in order to receive staking rewards.
```

2021-02-04 11:59 UTC, laboon commented on docs/learn-nominator.md
> +This number fluctuates day by day, and the most recent and up to date version can be
```suggestion
This number fluctuates every era, and the most recent and up to date version can be
```

2021-02-04 11:59 UTC, laboon commented on docs/learn-nominator.md
> +
```suggestion
See the [Election Solution Set](https://wiki.polkadot.network/docs/en/learn-nominator#the-election-solution-set) section on the Nominator page for more details.
```

2021-02-05 04:44 UTC, rskntroot commented
@laboon - thanks for the clarification, the changes read well.

2021-02-05 10:46 UTC, merged

2021-02-05 10:46 UTC, Swader commented
Nice, thanks