Add Centrifuge - chachacha
w3f/polkadot-wiki pull request #1747
Opened 2021-02-23 16:17 UTC by mikiquantum

@BenWhiteJam As discussed, please have a look and check if the wording is clear.

2021-02-23 22:54 UTC, NukeManDan commented
excited to see this as an option - thanks for offering this to the community!

2021-02-24 01:39 UTC, mikiquantum commented
@NukeManDan If I resolve the failing check running `node scripts/update-substrate.js` it brings up other changes. How should I proceed?

2021-02-24 01:41 UTC, NukeManDan requested changes

2021-02-24 01:41 UTC, NukeManDan commented on docs/build-parachains-rococo.md
> +    - Tag your question using the following user handle: @mikiquantum:matrix.org
Please don't bootstrap on our rococo channel. I would much rather have a dedicated one.

2021-02-24 01:42 UTC, NukeManDan commented on docs/build-parachains-rococo.md
> +    - Tag your question using the following user handle: @mikiquantum:matrix.org
it's fine to have people be in both, but you have a separate network here, just happens to be based on the same codebase :)

2021-02-24 02:04 UTC, mikiquantum commented
@NukeManDan Updated and added dedicated channel.

2021-02-24 02:51 UTC, NukeManDan commented
@mickstar LGTM!

2021-02-26 10:33 UTC, Swader commented
Needs prettify, then it's fine to merge. `npx prettify --save` should do IIRC.

2021-02-27 00:32 UTC, mikiquantum commented
@Swader I didn't find `prettify` in the npm dependencies. I ran this instead:
```
npx prettier --write docs/build-parachains-rococo.md
```
if that is not enough, would be good if you can point me to the correct way to install the prettify package.

2021-02-27 07:02 UTC, Swader commented
That's it, thanks!

2021-02-27 07:03 UTC, merged