added comparison to binance smart chain
w3f/polkadot-wiki pull request #1751
Opened 2021-02-24 13:38 UTC by midegdugarova

fixes #1555

2021-02-26 10:31 UTC, Swader commented
Is this something people are curious about? Seems a bit superfluous to me.

2021-03-01 09:14 UTC, laboon commented
I've gotten quite a few questions about BSC vs Polkadot. I think it makes sense to add it.

2021-03-01 10:13 UTC, Swader requested changes

2021-03-01 10:13 UTC, Swader commented on docs/learn-comparisons.md
> +[Binance Chain](https://www.binance.com) is a Proof of Staked Authority blockchain is used to
```suggestion
[Binance Chain](https://www.binance.com) is a Proof of Stake Authority blockchain used to
```

2021-03-01 10:13 UTC, Swader commented on docs/learn-comparisons.md
> +Dual Chain System. Binance Smart Chain is also a Proof of Staked Authority chain and allows users to
```suggestion
Dual Chain System. Binance Smart Chain is also a Proof of Stake Authority chain and allows users to
```

2021-03-01 10:13 UTC, Swader commented on docs/learn-comparisons.md
> +of the Cosmos architecture, interoperability of Binance Smart Chain is based on bridges. This means
interoperability with what?

2021-03-01 10:13 UTC, Swader commented on docs/learn-comparisons.md
> +and has much stronger trust assumptions.
```suggestion
and has much stronger economic security.
```

2021-03-01 10:13 UTC, Swader commented on docs/learn-comparisons.md
> +Scalability based on bridges relies on each bridged chain finding its own set of validators
```suggestion
Scalability based on bridges relies on each bridged chain finding its own set of validators,
```

2021-03-01 10:14 UTC, laboon requested changes

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +Relay chain, and as more validators join Polkadot, more parachains can be supported.
```suggestion
Relay Chain, and as the number of validators in the active set on Polkadot are increased, more parachains can be supported.
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +[Binance Chain](https://www.binance.com) is a Proof of Staked Authority blockchain is used to
```suggestion
[Binance Chain](https://www.binance.com) is a Proof of Staked Authority blockchain used to
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +exchange digital assets on the blockchain (Binance DEX). Binance Smart Chain is an
```suggestion
exchange digital assets on Binance DEX. Binance Smart Chain is an
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +Ethereum-compatible smart contract chain bridged to Binance Chain. Together they form the Binance
```suggestion
EVM-compatible smart contract chain bridged to Binance Chain. Together they form the Binance
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +create smart contracts and dApps.
```suggestion
create smart contracts and dapps.
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +all validators of both chains are also bridge operators, therewith the security of the system relies
```suggestion
all validators of both chains are also bridge operators, therefore the security of the system relies
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +on trusting validators. At the moment there are 21 Binance Smart Chain validator nodes.
```suggestion
on trusting validators. At the moment, there are 21 Binance Smart Chain validator nodes.
```

2021-03-01 10:14 UTC, laboon commented on docs/learn-comparisons.md
> +Polkadot has an entirely different purpose because it was built to connect and secure unique
```suggestion
Polkadot has an entirely different purpose, as it was built to connect and secure unique
```

2021-03-01 18:24 UTC, Swader approved these changes

2021-03-01 18:25 UTC, Swader commented
Looks OK to me, though I still fail to find a tangent between the two chains (to me this is like comparing MySQL and HTML) so not sure if we should point out that they have absolutely nothing in common, from mission to execution. I'll defer to @laboon for the final verdict here.

2021-03-03 12:33 UTC, laboon commented
I mean, it's basically a PoA'd Eth1 and we have a comparison to that... to many people a blockchain is a blockchain. I wouldn't recommend including comparisons to every chain out there, of course, but we get enough questions about it that I think it's worth it so we can just send a link to this instead of repeating ourselves.

2021-03-03 13:35 UTC, merged