Parainfo
w3f/polkadot-wiki pull request #1904
Opened 2021-03-25 11:02 UTC by Swader

- [ ] Check that the conditional rendering worked on merge
- [ ] Double check that there's no 404s

2021-03-25 17:46 UTC, jakehemmerle commented
build-parachains-rococo.md under "Lateral Transfers" : 'page here' link is broken. Not sure the context of it but it doesn't seem totally relevant anyway

2021-03-28 14:37 UTC, Swader commented
Leases on Kusama might extend to 3 months instead. Needs re-check before merge.

2021-04-01 13:41 UTC, laboon requested changes
Bruno - if you are OK with the changes I made, can you merge when ready?

2021-04-01 13:41 UTC, laboon commented on docs/build-build-with-polkadot.md
> +questions. As always, keep up to date with Polkadot and Kusamaby following the
```suggestion
questions. As always, keep up to date with Polkadot and Kusama by following the
```

2021-04-01 13:41 UTC, laboon commented on docs/build-parachains-rococo.md
> +
```suggestion

Note that these are example values; all are subject to change.

```

2021-04-01 13:41 UTC, laboon commented on docs/build-parachains-rococo.md
> +To start, we will only have 5 or 6 slots available on Rococo to ensure that the chain functions
```suggestion
To start, only 5 or 6 slots are planned to be available on Rococo to ensure that the chain functions
```

2021-04-01 13:41 UTC, laboon commented on docs/build-parachains-rococo.md
> +Would give Trick 100 lease periods, starting at lease period 0, but it wouldn't start until period 1
```suggestion
would give Trick 100 lease periods, starting at lease period 0, but it wouldn't start until period 1
```

2021-04-01 13:41 UTC, laboon commented on docs/learn-auction.md
> +{{ kusama: 24 weeks and divided into 6-week periods :kusama }}. Parachains may lease a slot for any
```suggestion
The slot durations are capped to {{ polkadot: 2 years and divided into 6-month periods :polkadot }}; 
Kusama slots durations and periods will be less than on Polkadot. Parachains may lease a slot for any
```

2021-04-01 13:41 UTC, laboon commented on docs/learn-auction.md
> +{{ kusama: 6-week duration for a total of 24 weeks :kusama }}_
```suggestion
_Each period of the range 1 - 4 represents a
{{ polkadot: 6-month duration for a total of 2 years :polkadot }}
or a shorter duration on Kusama_
```

2021-04-01 13:41 UTC, laboon commented on docs/learn-parachains.md
> +allowed to implement is that it must be verifiable by the Relay Chain validators. Verification most
```suggestion
state transition has occurred on a parachain. The key constraint regarding the logic of a parachain is
that it must be verifiable by the Relay Chain validators. Verification most
```
I believe there are other constraints here, e.g. in terms of relying on relay chain finalization,  block production time, etc.

2021-04-01 13:41 UTC, laboon commented on docs/learn-parachains.md
> +{{ polkadot: Polkadot :polkadot }} {{ kusama: Kusama :kusama }} is general over what the parachain
```suggestion
{{ polkadot: Polkadot :polkadot }} {{ kusama: Kusama :kusama }} is not overly particular about what the parachain
```

2021-04-06 06:55 UTC, merged