Add port 443 to the connection example.
w3f/polkadot-wiki pull request #2131
Opened 2021-06-07 20:02 UTC by davidrhodus

Most people are trying to connect using port 9944 and not 443 per the nginx configuration file. I encountered the same issue and found similar discussions on Discord.

2021-06-07 20:04 UTC, davidrhodus commented
@NukeManDan for your review 😀

2021-06-08 01:11 UTC, NukeManDan commented
I am not the pro on integrations, nor do I have push abilities for this repo. But this looks like a good suggestion to add to me 😀

2021-06-08 06:40 UTC, Swader requested changes
This assumes everyone is on 443, so still not good. I made a small change. Please merge, run prettier on it, and I'll merge the PR.

2021-06-08 06:40 UTC, Swader commented on docs/maintain-wss.md
> +address. Remember to prefix with `wss://example.com:443`.
```suggestion
address. Remember to prefix with `wss://` and if you're using the 443 port, append `:443`, like so: `wss://example.com:443`.
```

2021-06-08 15:19 UTC, merged