Update learn-accounts.md
w3f/polkadot-wiki pull request #2358
Opened 2021-07-19 09:36 UTC by DrW3RK

Added placeholder for content on Soft vs Hard Derivation paths

2021-07-19 15:07 UTC, DrW3RK commented
@laboon I made some preliminary updates to the page using your explanation in the issue. Let me know if I need to augment this with screenshots or a video. Also, let me know if you have any feedback on my writing style. Thanks!

2021-07-20 12:03 UTC, laboon requested changes

2021-07-20 12:03 UTC, laboon commented on docs/learn-accounts.md
> +"caution juice atom organ advance problem want pledge someone senior holiday very//polkadot//0"
```suggestion
"caution juice atom organ advance problem want pledge someone senior holiday very//0"
```
The "polkadot" isn't necessary, but is added by default by Parity Signer and probably some other wallets.

2021-07-20 12:03 UTC, laboon commented on docs/learn-accounts.md
> +"caution juice atom organ advance problem want pledge someone senior holiday very/polkadot/0"
```suggestion
"caution juice atom organ advance problem want pledge someone senior holiday very/0"
```

2021-07-20 12:03 UTC, laboon commented on docs/learn-accounts.md
> +If you would like to create another account for usage on the Polkadot chain, you can change the number at the end of the string above from 0 to 1. You can use any words or numbers in the derivation p
```suggestion
If you would like to create another account for usage on the Polkadot chain using the same seed, you can change the number at the end of the string above. For example, `/1`, `/2`, and `/3` will all create different derived accounts.

You can use any letters or numbers in the derivation path as long as they make sense to you; they do not have to follow any specific pattern. You may also combine multiple derivations in your path, as well. For instance, `//bill//account//1` and `//john/polkadot/initial` are both valid. You will need to know both the seed and the derivation path in order to recreate a derived account, so you should either use a well-defined sequence (e.g. //0, //1, //2...) or be sure to write down any derivation paths you use.

> It is not possible to generate a derived account without also knowing the derivation path.

### Soft vs. Hard Derivation

A soft derivation allows someone to potentially "go backwards" to figure out the private key of the initial account IF they know the private key of the derived account. It is also possible to determine that different accounts generated from the same seed are linked to that seed. A hard derivation path does not allow either of these - even if you know a derived private key, it's not feasible to figure out the private key of the root address, and it's impossible to prove that the first account is linked with the second. Both of these derivation methods have their use cases, given the private keys for all the derived accounts are fully secure. Unless you have a specific need for a soft derivation, it is recommended to generate the account using a hard derivation path.
```

2021-07-20 12:03 UTC, laboon commented on docs/learn-accounts.md
> +If you would like to create another account for usage on the Polkadot chain, you can change the number at the end of the string above from 0 to 1. You can use any words or numbers in the derivation p
We should also put the Soft vs. Hard description further up above (before we mention using / and //)

2021-07-20 12:03 UTC, laboon commented on docs/learn-accounts.md
> +If you would like to create and manage several accounts on the network using the same mnemonic seed phrase, you can use derivation paths. We can think of the derived accounts as the child accounts of
```suggestion
If you would like to create and manage several accounts on the network using the same seed, you can use derivation paths. We can think of the derived accounts as child accounts of the root account created using the original mnemonic seed phrase. Many Polkadot key generation tools support hard and soft derivation. For instance, if you intend to create an account to be used on the Polkadot chain, you can derive a **hard key** child account using **//** after the mnemonic phrase.
```

2021-07-20 12:04 UTC, laboon commented on docs/learn-accounts.md
> +private key. A typical mnemonic seed phrase generated by [the Subkey tool](https://substrate.dev/docs/en/knowledgebase/integrate/subkey) is shown below
```suggestion
private key. A typical mnemonic phrase generated by [the Subkey tool](https://substrate.dev/docs/en/knowledgebase/integrate/subkey) is shown below
```

2021-07-22 08:51 UTC, merged