Add treasury-funded wallets
w3f/polkadot-wiki pull request #2488
Opened 2021-08-17 15:32 UTC by laboon

DO NOT MERGE YET - NEEDS TO BE REVIEWED

Adds four Treasury-funded wallets/signers

2021-08-17 21:59 UTC, DannyS03 requested changes
If approved, commenting some brief suggestions.
- With this update we can remove the first "Note"
```
> Note that only Parity-developed wallets are listed on this page. Other third-party wallets are
> available, but are not listed here.
```
-  Moving the following section under the "Supported Wallets" heading
```
[Polkadot support](https://support.polkadot.network/) can provide assistance with issues related to
Polkadot-JS, the Polkadot{.js} extension, or Parity Signer. For other wallet software, you should
contact the developers of that wallet.
```

- Suggesting to update headers:
 ```
 # Polkadot Wallets
 ## Supported Wallets
 ## Treasury Funded Wallets
 ## Encryption Enhancement 
 ```

2021-08-17 21:59 UTC, DannyS03 commented on docs/build/build-wallets.md
> +### Polkadot or Kusama Treasury Funded Wallets
```suggestion
### Treasury Funded Wallets
```

2021-08-17 21:59 UTC, DannyS03 commented on docs/build/build-wallets.md
> +> Note that these third-party wallets have been funded by the community through either the Polkadot or Kusama [Treasury](learn-treasury). Web3 Foundation does not endorse these wallets, and you shoul
```suggestion
> NOTE: these third-party wallets have been funded by the community either through the Polkadot or Kusama [Treasury](learn-treasury). **Web3 Foundation does not endorse these wallets, and you should use your own due diligence in researching them.** The official Polkadot Support cannot provide support for issues with these wallets or other non-Parity developed wallets.
```

2021-08-18 06:58 UTC, laboon commented
Thanks Danny, I have accepted all of your suggestions (although since I force-pushed a new commit, I couldn't do it through the normal suggestions process)

2021-08-18 07:16 UTC, DrW3RK commented
Looks good. Merging with master

2021-08-18 07:16 UTC, merged