Fix PDK links
w3f/polkadot-wiki pull request #2593
Opened 2021-09-15 09:23 UTC by bdmason

2021-09-15 16:40 UTC, DannyS03 requested changes

2021-09-15 16:40 UTC, DannyS03 commented on docs/learn/learn-parachains.md
> +applications as parachains. For more info see [PDK content](/docs/build-pdk#parachain-development-kit-pdk).
```suggestion
applications as parachains. For more info see [PDK content](../build/build-parachains.md#parachain-development-kit-pdk).
```

2021-09-15 16:40 UTC, DannyS03 commented on docs/learn/learn-parachains.md
> +Please see the [Parachain Development page](/docs/build-pdk) for more information.
```suggestion
Please see the [Parachain Development page](../build/build-parachains.md) for more information.
```

2021-09-15 16:53 UTC, merged

2021-09-16 12:01 UTC, bdmason commented on docs/learn/learn-parachains.md
> +Please see the [Parachain Development page](/docs/build-pdk) for more information.
Neither does this one