Update Inflation Content on Staking Page
w3f/polkadot-wiki pull request #2644
Opened 2021-09-27 06:24 UTC by DannyS03

2021-09-29 22:53 UTC, jakehemmerle requested changes

2021-09-29 22:53 UTC, jakehemmerle commented on docs/learn/learn-staking.md
> +- 20% annual nominal return
is there a reason the `~` was removed?

2021-09-30 20:06 UTC, DannyS03 commented on docs/learn/learn-staking.md
> +- 20% annual nominal return
Oh, nope, I updated it

2021-09-30 20:07 UTC, jakehemmerle commented
lgtm!

2021-09-30 20:09 UTC, jakehemmerle approved these changes

2021-09-30 20:30 UTC, merged