Updated smart contracts page -  with PSPs and Libraries
w3f/polkadot-wiki pull request #2814
Opened 2021-11-15 14:12 UTC by PierreOssun

FYI Deleted the Ownable contract example as it was deprecated

2021-11-15 17:54 UTC, DannyS03 requested changes
Thanks @PierreOssun, left some suggestions

2021-11-15 17:54 UTC, salmad3 commented on docs/build/build-smart-contracts.md
> +Polkadot ecosystem got its own set of standards to fit ecosystem needs. Please visit [Polkadot Standards Proposals (PSPs) Github](https://github.com/w3f/PSPs).
```suggestion
Web3 Foundation supports proposals for Polkadot that define a set standards to fit ecosystem needs.
```

2021-11-15 17:54 UTC, DannyS03 commented on docs/build/build-smart-contracts.md
> +
```suggestion
```

2021-11-15 17:54 UTC, DannyS03 commented on docs/build/build-smart-contracts.md
> +These standards go through several acceptance phases, and the engagement of the whole community is needed to build valuable and future-proof standards.
```suggestion
These standards go through several acceptance phases, where the engagement of the whole community is needed to build valuable and future-proof standards.
```

2021-11-15 17:54 UTC, DannyS03 commented on docs/build/build-smart-contracts.md
> +
```suggestion
Please visit [Polkadot Standards Proposals (PSPs) Github](https://github.com/w3f/PSPs) for more information.
```

2021-11-15 17:54 UTC, DannyS03 commented on docs/build/build-smart-contracts.md
> +All the teams who will benefit from a standard needs to agree on its content.
```suggestion
All the teams who will benefit from a standard need to agree on its content.
```

2021-11-15 17:54 UTC, DannyS03 commented on docs/build/build-smart-contracts.md
> +- [Metis](https://github.com/patractlabs/metis): an Wasm contract standard library developed by Patract Labs
```suggestion
- [Metis](https://github.com/patractlabs/metis): a Wasm contract standard library, developed by [Patract Labs](https://patract.io/).
```

2021-11-16 09:52 UTC, PierreOssun commented
Thanks @DannyS03 for the suggestions

2021-11-16 14:35 UTC, DannyS03 approved these changes

2021-11-16 14:39 UTC, merged