Add Availability and Validity section
w3f/polkadot-wiki pull request #284
Opened 2020-02-20 13:58 UTC by lsaether

closes #82 
closes #221 
closes #282

2020-03-03 19:45 UTC, laboon requested changes
Overall looks good, just some small wording changes

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +- A merkle root of the block's erasure coded pieces.
```suggestion
- A Merkle root of the block's erasure coded pieces.
```

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +- A merkle root of any outgoing messages.
```suggestion
- A Merkle root of any outgoing messages.
```

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +validators must report that they possess their piece of the code word. Once
Can you add a brief explanation of what the "code word" is here or use a different word, since what the code word is is not defined until the next section?

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +data due to inconsistencies on the disk face such as dust particles or scratches.
This is really cool!

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +assumption that no more than 2/3 of the validators can be Byzantine.
Wait, I thought our assumption was that more than 1/5 were malicious and 2/3 are online?

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +if they find a misconduct has occurred during the production of a parachain.
```suggestion
if they find that misconduct has occurred during the production of a parachain.
```

2020-03-03 19:45 UTC, laboon commented on docs/learn-availability.md
> +will likely be the storage of maintaining the data for each of the parachains
```suggestion
will likely be the storage of data for each of the parachains
```

2020-03-04 13:32 UTC, Swader approved these changes

2020-03-04 13:32 UTC, Swader commented on docs/learn-availability.md
> +6. Invokation of a Byzantine fault tolerant _finality gadget_ to cement the chain.
```suggestion
6. Invocation of a Byzantine fault tolerant _finality gadget_ to cement the chain.
```

2020-03-04 13:32 UTC, Swader commented on docs/learn-availability.md
> +### On submission of an invalidity report
Should TODO this heading until it has content?

2020-03-04 15:38 UTC, lsaether commented on docs/learn-availability.md
> +assumption that no more than 2/3 of the validators can be Byzantine.
where does it say that? I've changed it to be open-ended for now

2020-03-04 15:39 UTC, lsaether commented
Going to say this is ready to merge as an initial page for now. The research write-up is still being formulated so there's not much more I think I can do here without that and implementation moving forward.

2020-03-05 09:47 UTC, merged