Add crust to build storage
w3f/polkadot-wiki pull request #2986
Opened 2022-01-24 07:02 UTC by badkk

2022-01-24 18:00 UTC, DannyS03 requested changes

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +### Crust
```suggestion
### Crust Network
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +The Crust protocol is 100% compatible with [IPFS](https://ipfs.io) procotol, it matches people who have hard drive space to spare with those users that need to store data or host content.
```suggestion
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +### Crust
As Crust is built on top of Substrate, can we add this under the Substrate Storage heading, after the content already included?

As in 

```
## Substrate Storage
...
...
### Crust Storage
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +[Crust](https://crust.network) provides a Web3.0 decentralized storage network for the Metaverse. It is designed to realize core values of decentralization, privacy and assurance. Crust supports mult
```suggestion
[Crust Network](https://crust.network) provides a decentralized storage network for the Metaverse. It is designed to realize core values of decentralization, privacy, and assurance. Crust supports multiple storage-layer protocols such as [IPFS](#ipfs-interplanetary-file-system) and exposes instant accessible on-chain storage functions to users. Crustʼs technical stack is also capable of supporting data manipulating and computing.
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +The Crust protocol is 100% compatible with [IPFS](https://ipfs.io) procotol, it matches people who have hard drive space to spare with those users that need to store data or host content.
Mention of IPFS earlier on which implies the following, and should be enough for the summary

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +
```suggestion
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +![xcmp-xstorage](../assets/build-3.png)
```suggestion
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +![xcmp-xstorage](../assets/build-3.png)
Because Crust network is not yet a parachain (aka. parachain candidate), providing a diagram like this on the Polkadot Wiki should be put on hold.

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +
```suggestion
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +### Crust
Also needs prettier

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +Crust builds on top of Substrate and provides a native cross-chain communnication pallet based on [XCMP](https://wiki.polkadot.network/docs/learn-crosschain) called [xStorage](https://github.com/crus
```suggestion
Crust provides a native cross-chain communication pallet based on [XCMP](https://wiki.polkadot.network/docs/learn-crosschain), called [xStorage](https://github.com/crustio/crust/tree/parachain/shadow/crust-collator/pallets/xstorage).
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +Crust also supports the majority contract platforms, including Ethereum/Solana/Near/Elrond/... with [cross-chain solution](https://wiki.crust.network/docs/en/buildCrossChainSolution).
```suggestion
The protocol also supports most smart contract platforms, including Ethereum, with its [cross-chain dStorage solution](https://wiki.crust.network/docs/en/buildCrossChainSolution).
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +> To learn more about Crust, check its [Decentralized Storage Market](https://wiki.crust.network/docs/en/DSM) and [Guaranteed Proof of Stake](https://wiki.crust.network/docs/en/GPoS)
```suggestion
> To learn more about Crust, check out the [Crust Network Wiki](https://wiki.crust.network/en).
```

2022-01-24 18:00 UTC, salmad3 commented on docs/build/build-storage.md
> +> Also, you can start with [Build-101](https://wiki.crust.network/docs/en/build101) to start integrating with Crust.
```suggestion
> Try integrating with Crust by following their [Crust Storage 101](https://wiki.crust.network/docs/en/build101) guide.
```

2022-01-24 18:04 UTC, DannyS03 commented
Thanks @badkk, left some suggestions

2022-01-26 06:03 UTC, badkk commented on docs/build/build-storage.md
> +### Crust
Yeah, I think it's reasonable!

2022-01-26 06:04 UTC, badkk commented on docs/build/build-storage.md
> +![xcmp-xstorage](../assets/build-3.png)
Deleted, will put it after we got polkadot parachain slot

2022-01-26 06:04 UTC, badkk commented
> Thanks @badkk, left some suggestions

All resolved, please check it again

2022-01-27 08:12 UTC, DannyS03 requested changes

2022-01-27 08:12 UTC, DannyS03 commented on docs/build/build-storage.md
> +Crust provides a native cross-chain communnication communication pallet based on [XCMP](https://wiki.polkadot.network/docs/learn-crosschain), called [xStorage](https://github.com/crustio/crust/tree/p
We need to remove "The basic idea of xStorage shows below:" and "build-3.png"

2022-01-27 08:12 UTC, DannyS03 commented on docs/build/build-storage.md
> +
Still needs pretty: https://github.com/w3f/polkadot-wiki#formatting

2022-01-28 03:22 UTC, badkk commented
@DannyS03 Already resolved!

2022-01-28 12:26 UTC, DannyS03 commented on docs/build/build-storage.md
> +[Crust Network](https://crust.network) provides a Web3.0 decentralized storage network for the Metaverse. It is designed to realize core values of decentralization, privacy, and assurance. Crust supp
```suggestion
[Crust Network](https://crust.network) provides a Web3.0 decentralized storage network for the Metaverse. 
It is designed to realize core values of decentralization, privacy, and assurance. 
Crust supports multiple storage-layer protocols such as [IPFS](#ipfs-interplanetary-file-system), 
and exposes instant accessible on-chain storage functions to users. Crustʼs technical stack is also 
capable of supporting data manipulating and computing.
```

2022-01-28 12:32 UTC, DannyS03 commented on docs/build/build-storage.md
> +
Still need to format the section so it is consistent with the style guide: 
![image](https://user-images.githubusercontent.com/25497083/151547067-5c469217-7d5d-4745-bfc0-1c56137b653f.png)

2022-01-30 05:51 UTC, merged