Revamping the build section
w3f/polkadot-wiki pull request #30
Opened 2019-10-01 09:18 UTC by lsaether

2019-10-06 10:10 UTC, ansonla3 reviewed
just minor stuff, overall looks good

2019-10-06 10:10 UTC, ansonla3 commented on docs/build-build-with-polkadot.md
> +For more information on how parathread per-block auctions work, see the more detailed [parathread](learn-parathread) page.
miss "s": learn-parathreads

2019-10-06 10:10 UTC, ansonla3 commented on docs/build-index.md
> +- [Networks](build-networks) - How to connect to the different networks.
build-networks - file does not exist anymore

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
>  - Substrate: **1.0.0-rc**
There have been other tags since, both RC and seemingly a stable 1.0, though missing a release. Does this indicate what's running on Kusama/Alexander?

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +connect to Polkadot and become a parachain. Substrate has had a 1.0.0 release, which settled its API for the time
See comment above. Substrate has had a 1.0 release, so not RC?

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +This module allows for smart contracts compile to Wasm code to be deployed to the chain and instantiated by users.
```suggestion
This module allows for smart contracts compiled to Wasm code to be deployed to the chain and instantiated by users.
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +To facilitate development of Wasm smart contracts, Parity is also developing ink!, a domain specific language built
```suggestion
To facilitate development of Wasm smart contracts, Parity is also developing [ink!](https://github.com/paritytech/ink), a domain specific language built
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +own parachain, or as a parathread. There are trade-offs when working with either any of these and reading this section will help you
```suggestion
own parachain, or as a parathread. There are trade-offs when working with each of these and reading this section will help you
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +You may also decided to harness a combination of parachain, parathread, and smart contract. If you have certain logic that requires
```suggestion
You may also decide to harness a combination of parachain, parathread, and smart contract. If you have certain logic that requires
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +but in order to do this requires some additional infrastructure. It needs some way to stay up to date with the most
```suggestion
but doing this requires some additional infrastructure. A validator needs some way to stay up to date with the most
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +This is where the collator node comes in to play, it the maintainer of your parachain and performs the critical action
```suggestion
This is where the collator node comes into play. A collator is a maintainer of your parachain and performs the critical action
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +[contract](https://github.com/paritytech/substrate/tree/master/srml/contract) module in the core SRML will support
```suggestion
[contract](https://github.com/paritytech/substrate/tree/master/srml/contracts) module in the core SRML will support
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +support compilation to Wasm.
```suggestion
supports compilation to Wasm.
```

2019-10-07 09:39 UTC, Swader commented on docs/build-build-with-polkadot.md
> +to keep as much data off-chain as possible. You may consider using IPFS or Storj to keep the data and submitting only
```suggestion
to keep as much data off-chain as possible. You may consider using [IPFS](https://ipfs.io/) or [Storj](https://storj.io/) to keep the data and submitting only
```

2019-10-07 09:39 UTC, Swader commented on docs/build-examples-index.md
> +- [Substrate TCR](https://github.com/substrate-developer-hub/substrate-tcr)- Token curated registry as a runtime module.
```suggestion
- [Substrate TCR](https://github.com/substrate-developer-hub/substrate-tcr) - Token curated registry as a runtime module.
```

2019-10-07 09:39 UTC, Swader commented on docs/build-examples-index.md
>  - [Shasper](https://github.com/paritytech/shasper)- Eth2.0 implemented as Substrate runtime.
```suggestion
- [Shasper](https://github.com/paritytech/shasper) - Eth2.0 implemented as Substrate runtime.
```

2019-10-14 00:38 UTC, laboon commented on docs/build-build-with-polkadot.md
>  - Substrate: **1.0.0-rc**
Kusama looks to be running on substrate 2.0 (master branch) but 1.0 is the latest official substrate release, and also what alexander is running on.

2019-10-14 01:03 UTC, laboon requested changes
Overall looks great!  I had some suggestions in a few places, all relatively minor.

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
>  - Substrate: **1.0.0-rc**
```suggestion
- Substrate: **1.0.0**
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +connect to Polkadot and become a parachain. Substrate has had a 1.0.0 release, which settled its API for the time
Added a suggestion to remove `-rc`

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +The lower costs of parathreads are due to the nature that parathreads will only produce a block when they need to, unlike
```suggestion
The lower costs of parathreads are due to the fact that parathreads will only produce a block when they need to, unlike
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +The lower costs of parathreads are due to the nature that parathreads will only produce a block when they need to, unlike
Although we may want to specify that they only generate a block _recorded by the relay chain_ -  AFAIK there's nothing stopping from a parathread internally generating _n_ (where _n_ > 1) blocks and then only adding a digest when it connects to the relay chain, right?

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +On the Polkadot mainnet, there will be one or more parachains that act as smart contract platforms. Smart contracts are
```suggestion
On the Polkadot mainnet, there can be parachains that act as smart contract platforms. Smart contracts are
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +chain, they have smooth interoperability with other smart contracts. However, they will always be constrained and
```suggestion
chain, they can have smooth interoperability with other smart contracts on the same chain. However, they will always be constrained and
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +quick iterations. A smart contract MVP could be created to gauge user interest before putting in the fuller work to
```suggestion
quick iterations. A smart contract MVP could be created to gauge user interest before putting in the work to
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +Parachains will grant the creators more space to build the monetary system of the chain from the ground up. They will
```suggestion
Parachains grant the creators more space to build the monetary system and other aspects of the chain from the ground up. They will
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +platform. Parachains also offer more in the form of governance and can perform complete upgrades in a less
```suggestion
platform. Parachains also offer more flexibility in the form of governance and can perform complete upgrades in a less
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +contracts. Parachains in comparison lack a gas metering system entirely and could potentially be vulnerable to bugs
```suggestion
contracts. However, unlike smart contracts, parachains lack a mandatory gas metering system entirely and could potentially be vulnerable to bugs
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +only triggers once every 24 hours (this mostly makes sense if the data is useful to other players in the Polkadot
```suggestion
only triggers once every 24 hours (this makes the most sense if the data is useful to other players in the Polkadot
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +Most likely you’ve already realized that your application is better suited to be one or the other (or a hybrid of them all
```suggestion
Most likely you’ve already realized that your application is better suited to be one or the other (or a hybrid of them both
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +> applies just as well to parathreads. However, they are cheaper to deploy and maintain. So if they had a column
```suggestion
> apply just as well to parathreads. However, they are cheaper to deploy and maintain. So if they had a column
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +> applies just as well to parathreads. However, they are cheaper to deploy and maintain. So if they had a column
```suggestion
> apply just as well to parathreads. However, parathreads are cheaper to deploy and maintain. So if they had a column
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +This guide now splits into two sections depending on whether you’ve decided on smart contract or parachain to build
```suggestion
This guide now splits into two sections depending on whether you’ve decided on a smart contract or a parachain to build
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +> grants to teams who are doing this, learn more and apply on the [W3F grants page](https://grants.web3.foundation).
Should we mention Gossamer et al. here?

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +Substrate comes with its own networking layer built-in but unfortunately only supports solo chains. However, there is
```suggestion
Substrate comes with its own networking layer built-in but unfortunately only supports solo chains (that is, chains which do not connect to the relay chain). However, there is
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +This means that even work spent developing on these platforms today may be applicable to running on Polkadot in the
```suggestion
This means that work spent developing on these platforms today may be applicable to running on Polkadot in the
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +you will send a special transaction that will CREATE the smart contract on the ledger. You will likely need to pay an
```suggestion
you will send a special transaction that will create the smart contract on the ledger. You will likely need to pay an
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
> +For the interested developers, they can get started writing smart contracts using Ink by studying the
```suggestion
For interested developers, they can get started writing smart contracts using Ink by studying the
```

2019-10-14 01:03 UTC, laboon commented on docs/build-build-with-polkadot.md
>  - [Substrate contracts module](https://github.com/paritytech/substrate).
```suggestion
- [Substrate contracts module](https://github.com/paritytech/substrate/tree/master/srml/contracts).
```

2019-10-14 06:46 UTC, lsaether commented on docs/build-build-with-polkadot.md
> +The lower costs of parathreads are due to the nature that parathreads will only produce a block when they need to, unlike
That's true, good point.

2019-10-14 06:50 UTC, lsaether commented on docs/build-index.md
> +- [Networks](build-networks) - How to connect to the different networks.
```suggestion
```

2019-10-14 06:52 UTC, lsaether commented on docs/build-build-with-polkadot.md
> +> grants to teams who are doing this, learn more and apply on the [W3F grants page](https://grants.web3.foundation).
Gossamer is not ready for developer use afaik. Will look into it and add more info if applicable.

2019-10-14 06:52 UTC, lsaether commented on docs/build-build-with-polkadot.md
> +For more information on how parathread per-block auctions work, see the more detailed [parathread](learn-parathread) page.
```suggestion
For more information on how parathread per-block auctions work, see the more detailed [parathread](learn-parathreads) page.
```

2019-10-14 06:57 UTC, lsaether commented
Comments have been addressed and conflicts resolved.

2019-10-14 09:10 UTC, laboon commented on docs/build-build-with-polkadot.md
> +> grants to teams who are doing this, learn more and apply on the [W3F grants page](https://grants.web3.foundation).
Yeah, I meant that we could mention some of the upcoming projects by name instead of just saying that Substrate is the only one.  But I don't think it's a big deal and should stop this PR, we can add them in later one they're publicly ready.

2019-10-14 09:11 UTC, laboon commented
👍 LGTM, merge if you're ready!

2019-10-14 09:11 UTC, laboon approved these changes
👍

2019-10-14 09:32 UTC, laboon commented
Oh, missed that Substrate version issue - 1.0.0 seems to the be the latest and "official-est" release

2019-10-14 16:45 UTC, merged