Root Origin update
w3f/polkadot-wiki pull request #3017
Opened 2022-02-07 17:17 UTC by DrW3RK

Reference Issue: https://github.com/w3f/polkadot-wiki/issues/3014

2022-02-07 22:18 UTC, DannyS03 requested changes
Need to change italic format back to "*" as it will conflict with the conditional rendering on the page

2022-02-07 22:18 UTC, DannyS03 commented on docs/general/glossary.md
> +A system level [origin](##Origin) in [Substrate](##Substrate). This is the highest privilege level
```suggestion
A system-level [origin](##Origin) in [Substrate](##Substrate). This is the highest privilege level
```

2022-02-08 09:33 UTC, DrW3RK commented
_Need to change italic format back to "*" as it will conflict with the conditional rendering on the page_

Do you happen to know how to do it? If so, please do it. I reverted the prettify commit and added your suggestion

2022-02-08 12:48 UTC, DannyS03 approved these changes

2022-02-08 12:48 UTC, merged