Update unstable Polka-dot JS url (https://polkadot.js.org/apps/)
w3f/polkadot-wiki pull request #3018
Opened 2022-02-07 20:32 UTC by muddlebee

Previous : https://polkadot.js.org/apps/
New : https://dotapps.io/ 

Update unstable URL( https://polkadot.js.org/apps/ ) to the stable URL ( https://dotapps.io/ ) as mentioned in the core repository https://github.com/polkadot-js/dotapps.io

2022-02-07 20:33 UTC, muddlebee commented
hey @DrW3RK 👋 

Can you please see if this is okay? People have been reporting this unstability over discord group as well :) 
This works as a long term fix.

2022-02-08 09:41 UTC, DrW3RK commented
@muddlebee Thanks for reporting! What unstability are you referring to? https://polkadot.js.org/apps/ should open as expected and https://dotapps.io/  is listed on top right.

https://dotapps.io/  is an IPFS version that is updated more or less on a weekly basis. Instead of replacing the original link, providing and alternative in the doc might be a better idea!

2022-02-08 10:18 UTC, DrW3RK commented on docs/learn/learn-account-generation.md
> +Navigate to [Polkadot-JS Apps](https://dotapps.io/) and click on "Accounts" underneath the
Navigate to [Polkadot-JS Apps](https://polkadot.js.org/apps) (or [dotapps.io](https://dotapps.io/)) and click on "Accounts" underneath the

2022-02-08 10:23 UTC, DrW3RK requested changes
It does not matter if it is https://polkadot.js.org/apps or https://dotapps.io - both of them point to the same repo. If there is an issue with repo hosting service for https://polkadot.js.org/apps then the IPFS hosted version  https://dotapps.io comes to the rescue.

If https://polkadot.js.org/apps takes too long to load, then the issue might be with the load on the RPC node it is connected to. Simply switching it to a different on the top left dropdown should fix that issue

2022-02-08 14:33 UTC, muddlebee commented
hey @DrW3RK 

https://polkadot.js.org/apps/ -> this link never works for me :| and for many others as well at the discord group. How to fix this?

![Screenshot 2022-02-08 at 8 02 34 PM](https://user-images.githubusercontent.com/8139783/153008012-61b74006-297e-4edd-b18f-c9e12968f262.png)

2022-02-08 14:35 UTC, muddlebee commented
@DrW3RK https://polkadot.js.org/apps/

Sometimes it works. Sometimes it doesn't. Now I am able to open after a few clicks and many have reported. Can we look deeper into this? I can check if you re-direct me to the appropriate resource.

2022-02-08 14:38 UTC, muddlebee commented
@DrW3RK anyway I have made the changes you suggested 🚀

2022-02-08 16:15 UTC, DrW3RK commented
Thanks @muddlebee 

Yeah, the right place to report this issue is Polkadot JS Apps repo https://github.com/polkadot-js/apps . It is important to do some root cause analysis for the blank screen issue. Check out these two issues and see if either of those is a reason

https://github.com/polkadot-js/apps/issues/6900
https://github.com/polkadot-js/apps/issues/6517

For now, I will merge your commits to the Wiki

2022-02-08 16:20 UTC, DrW3RK approved these changes

2022-02-08 16:25 UTC, merged