Update build-data.md
w3f/polkadot-wiki pull request #3061
Opened 2022-02-28 02:40 UTC by Moehringen

I have added one line for the Web3Go project, which is the data analytics platform on Polkadot.

2022-02-28 20:01 UTC, DannyS03 requested changes
Thanks @Moehringen, left some comments

2022-02-28 20:01 UTC, DannyS03 commented on docs/build/build-data.md
> +[Web3GO](https://web3go.xyz/) Web3Go is a data analytics platform on Polkadot focused on building professional dashboards and providing the tools and API to help users easily visualize, curate, and s
```suggestion
[Web3GO](https://web3go.xyz/) is a Polkadot-based open data analytics platform that provides infrastructure and tooling to help users visualize, curate, share, and analyze on-chain data.
```

2022-02-28 20:01 UTC, DannyS03 commented on docs/build/build-data.md
> +
```suggestion
```

2022-02-28 20:01 UTC, DannyS03 commented on docs/build/build-data.md
> +
also needs formatting (prettify)

2022-03-01 01:24 UTC, Moehringen reviewed
thanks!

2022-03-01 02:05 UTC, DannyS03 commented on docs/build/build-data.md
> +[Web3GO](https://web3go.xyz/) is a Polkadot-based open data analytics platform that provides infrastructure and tooling to help users visualize, curate, share, and analyze on-chain data.
```suggestion
[Web3GO](https://web3go.xyz/) is a Polkadot-based open data analytics platform that provides 
infrastructure and tooling to help users visualize, curate, share, and analyze on-chain data.
```

2022-03-01 02:22 UTC, merged