Setting sub-identities using Ledger
w3f/polkadot-wiki pull request #3107
Opened 2022-03-11 11:04 UTC by DrW3RK

PR for this issue - https://github.com/w3f/polkadot-wiki/issues/3106

2022-03-11 14:36 UTC, laboon requested changes
We should also include this on https://wiki.polkadot.network/docs/kusama-ledger

I would prefer to see this information in text form there (step by step instructions like https://wiki.polkadot.network/docs/kusama-ledger#removing-expired-democracy-locks) and then linking to the video as supplemental information.

2022-03-13 11:20 UTC, DrW3RK commented
@laboon Here are the changes made -

- Added step-by-step text instructions for setting sub-identity
- Added relevant screenshots
- Updated the instructions on Sub Accounts wiki section with screenshots and video link
- Added references to Sub Accounts wiki section instead of the video

2022-03-14 10:30 UTC, laboon requested changes

2022-03-14 10:30 UTC, laboon commented on docs/general/kusama/kusama-ledger.md
> +You should now see the sub-identity displayed on-chain. You need to aware that 0.033 KSM is reserved for setting
"0.033" and "0.006" should be variables, not hard-coded.

Otherwise looks good to me!

2022-03-14 11:10 UTC, laboon approved these changes

2022-03-14 11:15 UTC, merged