Account generation page
w3f/polkadot-wiki pull request #311
Opened 2020-03-09 18:03 UTC by lsaether

2020-03-09 18:45 UTC, Swader commented
Can you try rebasing if this was made before the link checker merge so we can see if it's okay for internal links checking?

2020-03-16 10:19 UTC, laboon requested changes
Two minor changes, otherwise looks good

2020-03-16 10:19 UTC, laboon commented on docs/learn-account-generation.md
> +## Coinbase
Let's remove the Coinbase custody information here.  It's not really specifically about "account generation".

2020-03-16 10:19 UTC, laboon commented on docs/learn-account-generation.md
> +### Store the Key Safely
We have the same information about securing the key safely in multiple places.  I think we should just move this to one place at the top.  It made more sense on the claims page when people were taking different "paths" but here it just seems redundant.

2020-03-16 10:49 UTC, laboon approved these changes

2020-03-16 10:51 UTC, merged