Update backing up and restoring page of the accounts section for the …
w3f/polkadot-wiki pull request #3121
Opened 2022-03-17 21:18 UTC by emresurmeli

1. Link mnemonic phrase
2. Update images to recent version of the polkadot.js UI
3. Add new section "Transferring Polkadot-JS Apps Accounts/Addresses From One Computer to Another"

2022-03-21 13:06 UTC, DrW3RK requested changes
Minor updates to the tutorial instructions (I ran through all the steps and they work)

Also, @emresurmeli - As we recommend usage of Polkadot-JS Extension, it makes sense to update the tutorial with instructions on how to restore the account using mnemonic phrase on the extension rather than on the Polkadot JS Apps UI. It is okay to retain the existing instructions stating that it is always recommended to use the extension instead of the Apps UI

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +![restore-using-json](../assets/accounts/backing_up_and_restoring/via_existing_seed_1.png)
The alt text for the three newly added images should provide context for the image. Right now it is restore-using-json for all the three image files

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +9. Set a variable raw equal to the JSON you created =
```suggestion
9. Set a variable raw equal to the string from the text file
```

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +4. Copy and paste the returned string to a text editor.
```suggestion
4. Copy and paste the returned string to a text editor and save the file.
```

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +6. Save and send that JSON file to the new computer.
```suggestion
6. Save and send that file with the copied string to the new computer.
```

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +8. Open the Javascript console
```suggestion
8. Open the Javascript console on the browser (Available in Developer Tools)
```

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +2. Go to JavaScript console (on Brave, NOT on Polkadot-JS)
```suggestion
2. Go to JavaScript console on the browser (Available in Developer Tools)
```

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +3. Type in the command JSON.stringify(localStorage)
Just the way code is shown distinct from the text in the steps below, ensure this line below is displayed as code

JSON.stringify(localStorage)

2022-03-21 13:06 UTC, profradha commented on docs/learn/learn-account-restore.md
> +10. Run the following code:
```suggestion
10. Run the following code on the console:
```

2022-03-25 20:25 UTC, DrW3RK approved these changes

2022-03-25 20:37 UTC, merged