Update Bridges section to be Interoperability section, with XCM and B…
w3f/polkadot-wiki pull request #3202
Opened 2022-04-09 04:13 UTC by emresurmeli

2022-04-11 13:11 UTC, DannyS03 requested changes

2022-04-11 13:11 UTC, DannyS03 commented on docs/learn/learn-architecture.md
> +XCM, short for cross-consensus messaging is a format, and not a protocol. It does not assume anything
```suggestion
XCM, short for cross-consensus messaging, is a format and not a protocol. The format does not assume anything
```

2022-04-11 13:11 UTC, DannyS03 commented on docs/learn/learn-architecture.md
> +about the reciever or senders consensus mechanism, it just cares about the format in which the messages
```suggestion
about the receiver or senders consensus mechanism, it only cares about the format in which the messages
```

2022-04-11 13:11 UTC, DannyS03 commented on docs/learn/learn-architecture.md
> +must be formatted in. This format is the bread and butter of how parachains can communicate with one
```suggestion
must be formatted in. XCM is how parachains will be able to communicate with one
```

2022-04-11 14:16 UTC, DrW3RK commented
The article can benefit from a summary of these discussions
https://substrate.stackexchange.com/questions/151/what-is-the-xcm-format-on-polkadot
https://substrate.stackexchange.com/questions/591/what-is-the-difference-between-xcm-and-xcmp

2022-04-13 03:17 UTC, DannyS03 requested changes

2022-04-13 03:17 UTC, salmad3 commented on docs/learn/learn-architecture.md
> +the format in which the messages must be structured in. XCM format is how parachains will be able to
```suggestion
the format in which the messages must be structured in. The XCM format is how parachains will be able to 
```

2022-04-13 03:17 UTC, DannyS03 commented on docs/learn/learn-architecture.md
> +communicate with one another. Different from XCMP which is short for cross-chain messaging protocol,
```suggestion
communicate with one another. Different from XCMP, which is short for cross-chain messaging protocol,
```

2022-04-13 03:17 UTC, DannyS03 commented on docs/learn/learn-architecture.md
> +XCM is what gets delivered, and XCMP is the delivery mechanism. Best way to learn more about XCM by
```suggestion
XCM is what gets delivered, and XCMP is the delivery mechanism. The best way to learn more about XCM is by
```

2022-04-13 20:47 UTC, DannyS03 approved these changes

2022-04-13 20:48 UTC, merged