General link cleanup in 'Learn Governance'
w3f/polkadot-wiki pull request #3433
Opened 2022-06-23 22:41 UTC by alfarok

### Task
This PR addresses [#3041](https://github.com/w3f/polkadot-wiki/issues/3041)
and resolves a couple of broken link outlined in #3136 

### Goals

- [ ] The current [voluntary-locking](https://wiki.polkadot.network/docs/learn-governance#voluntary-locking) section provides details regarding how long a lock period will persist.
- [x] Lock period length is sourced directly from the [polkadot parameters page](https://wiki.polkadot.network/docs/maintain-polkadot-parameters) and [kusama parameters page](https://guide.kusama.network/docs/kusama-parameters/)or links to it
- [x] Several small link fixes and formatting unification

2022-06-24 15:07 UTC, alfarok commented on docs/general/grants.md
> -- [Darwinia Grants Program](https://docs.darwinia.network/developers/dev-bounty#grant-program)
It appears like they have removed this page

2022-06-24 15:08 UTC, alfarok commented on docs/maintain/kusama/maintain-guides-how-to-validate-kusama.md
> -[Kusama forum](https://forum.kusama.network/) or in the
forum no longer relevant

2022-06-27 13:33 UTC, DrW3RK commented
Good work with catching broken links! Just merged another PR that fixed some of them.

When a reader lands on the voluntary locking section, the information presented there should be intuitive. Right now, the reader has to first look at the table that has locked periods and then read further into the document to access the links where the number of days in a lock period are listed.

To improve the experience, we can add an extra column here with the days displayed through conditional rendering for Polkadot and Kusama.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/86818441/175953063-861a07a4-49a8-459e-86f6-43033efea8bd.png">

If you like to push further and explore more, you could also fetch the voteLockingPeriod from the chain state and use it to calculate the values rendered in the table

<img width="1954" alt="image" src="https://user-images.githubusercontent.com/86818441/175953343-52a74d55-08fb-4359-9e5f-23bc5a106e15.png">

Also, limit a PR to address a single issue and avoid mixing it up with unrelated issues. We can discuss further during the team sync. Talk to you soon!

2022-06-27 13:40 UTC, DrW3RK requested changes
Added a comment earlier. You can create a separate PR for modifying governance page and limit this PR to broken link fixes

2022-06-27 13:40 UTC, DrW3RK commented on docs/learn/learn-governance.md
> +{{ polkadot: [Polkadot Parameters page](../maintain-polkadot-parameters/#governance) :polkadot }}{{ kusama: [Kusama Parameters page](../kusama-parameters/#governance) :kusama }}.
Lock period length is not referenced anywhere in the parameters page

2022-06-27 13:45 UTC, DrW3RK commented
Forgot to link the PR that was already merged that was addressing broken links on Substrate docs https://github.com/w3f/polkadot-wiki/pull/3437

2022-06-27 14:00 UTC, alfarok commented
> I have some feedback regarding the governance page update. When a reader lands on the voluntary locking section, the information presented there should be intuitive. Right now, the reader has to first look at the table that has locked periods and then read further into the document to access the links where the number of days in a lock period are listed.
> 

Thanks for the feedback here!  I wasn't sure exactly based on the original issue how much detail was required or how common it was to duplicate the information vs linking back and forth.  I will work on getting this polished.

2022-06-27 14:02 UTC, alfarok commented
@DrW3RK Also thank you for pointing me at #3437 I wasn't aware of this.  I think it is still missing updates from several old substrate docs but I will pull in those changes now that it's merged to compare and report back.

2022-06-27 14:15 UTC, DrW3RK commented
Sure! I personally think some level of redundancy helps in the sections of the Wiki to minimize the number of links the reader has to click through. So, feel free to add redundant content in the context of the particular sections in the Wiki and then link it to the exclusive section for further reading.

I always try to read the PR changes from the user perspective and when I clicked through the parameters link to find information about voting lock period and I could not find any. I'd encourage you to wear the shoes of a general reader who would be using the Wiki when adding the content. Talk to you tomorrow!

2022-06-27 18:22 UTC, alfarok commented
@DrW3RK I moved the other work into a separate PR #3442 for clarity.  Originally when I thought this task just required referencing the parameters pages I thought it made sense to do all the link restoration together but I totally agree separate PR's is the way the go.

One more question related to this work.  Can you point me to an existing example where dynamic values are rendering in markdown?  I would like to try fetch the `voteLockingPeriod` from the chain state but didn't know this was possible in markdown.  Is it a feature of docusaurus?

2022-06-28 13:51 UTC, alfarok commented on scripts/inject-dict.json
> +    "filters": ["blocksToDays"]
Ah okay this is good to know.  I also see from your previous commit that the table is still only rendering Polkadot values but using conditional rendering with a table doesn't seem to work.  I was trying to see if I could find another existing example in the repo of this.

2022-06-28 14:10 UTC, profradha commented on scripts/inject-dict.json
> +    "filters": ["blocksToDays"]
Yeah. Conditional rendering does not work in the tables with the way we have written the code https://github.com/w3f/polkadot-wiki/blob/70c12a9a313727e9011ef0a232a56e898cb20260/scripts/inject.mjs#L141 as the markdown syntax for table rendering may be messing with it. 

Did not want to waste much time on this. Instead, I created variables and they are usually rendered based on the locale. This was easier. Explore the code I just pushed.

2022-06-28 14:12 UTC, DrW3RK approved these changes
Looks good to me!

2022-06-28 14:15 UTC, DrW3RK commented
It is a recommended practice to use variables, instead of hard coded values in the Wiki. It is an efficient way to change them everywhere at once.

2022-06-28 16:21 UTC, merged