Organize and unify formatting for fetched and default constant values
w3f/polkadot-wiki pull request #3464
Opened 2022-07-01 18:08 UTC by alfarok

This PR addresses #3447 and accomplishes the following:

- [x] Cleans up conditional logic in existing `fetch.mjs`
- [x] Unifies the formatting of fetched and default values
- [x] Removes extra verbose logging for less unnecessary console noise
- [x] Refactors some naming for added clarity
- [x] Add more comments to outline how the constants are processed for future reference
- [x] Tested that output of `computed-dict.json` returns the same values for Polkadot and Kusama + additional formatting
- [x] Tested that all default value format to expected constants for both Polkadot and Kusama

- [ ] Determine why default values are used when fetch paths are available
- [ ] Fix broken fetch paths

Example of 4 default values previously vs updated:
![Formatting-Default-Values](https://user-images.githubusercontent.com/13341935/176947619-ca2aa544-da07-49b8-a9b2-9954d64d96a5.png)

2022-07-01 18:24 UTC, alfarok commented
These are the constants that have fetch paths but fail to retrieve valid data, therefore fallback to defaults:

1) tip_deposit_amount
2) tip_finders_fee
3) identity_reserve_funds
4) identity_sub_reserve_funds
5) identity_field_funds

Looking into the reasoning of this now that I understand the conditional flow.

2022-07-01 18:55 UTC, alfarok commented
Sorry the diff is slightly confusing on this one but it should simplify adding and maintaining constants in the future.  It might be easier to look at the updated `fetch.mjs` file individually prior to looking at the diff.  Let me know if you have questions!

2022-07-04 10:30 UTC, DrW3RK requested changes
Good work! Everything comiples as expected and the values seem correct, except for spend period which still shows in blocks in the log (but I see the correct value 24 on computed-dict.json. I'm seeing this when I run `yarn polkadot:inject`

<img width="365" alt="image" src="https://user-images.githubusercontent.com/86818441/177136398-878e5e25-842d-4b9d-871c-fd708c7de3ec.png">

Could you please double check and let me know if there is something to be addressed.

2022-07-05 13:35 UTC, alfarok commented
> Could you please double check and let me know if there is something to be addressed.

Interesting, I wasn't familiar with the yarn `polkadot:inject` command yet.  It looks like `inject.mjs` is responsible for this behavior.  It contains almost the same logic as `fetch.mjs` but there are a few differences.  It looks like even prior to these changes you could potentially get slightly different results, one example is when the human readable option is set for Kusama.

fetch.mjs:
```js
case "humanReadableToken":
      let decimals = 6
      if (wiki === "polkadot") {
        decimals = 3;
      }

      value = (value / values[wiki].precision).toFixed(decimals) + " " + values[wiki].symbol;
      break;
```

inject.mjs:
```js
case "humanReadableToken":
      value = (value / values[wiki].precision).toFixed(3) + " " + values[wiki].symbol;
      break;
``` 

I will spend a little time looking into how difficult it would be to consolidate the core logic in a consistent manner.

2022-07-05 17:57 UTC, alfarok commented
@DrW3RK I was able to achieve the expected results by removing the `inject.mjs` file and adding an additional command line argument to `fetch.mjs` (`--inject`).  The constants dictionary is calculated every time fetch is invoked but the injection flag must be set to `true` for the constants to be inserted into the html.  This should operate the same as having the 2 files, without having duplicate logic for the calculation of the constants.  The commands in the `package.json` were also updated so build, start, and inject should all work with the same legacy syntax.

![image](https://user-images.githubusercontent.com/13341935/177387622-6a397d85-f94b-4f38-bc09-9b273cf54131.png)

2022-07-05 18:10 UTC, alfarok commented on scripts/fetch.mjs
> +      }
This is the only logic that was unique to `inject.mjs` that wasn't already in `fetch.mjs`, everything else was duplicated.  I haven't verified this logic but it produces the same results as the previous state.

2022-07-05 18:52 UTC, DrW3RK approved these changes
Looks good to me! Thanks @alfarok

2022-07-05 19:20 UTC, alfarok commented
I was trying to validate the logic in `inject` and I think in the current state it only logs the calculated constants.  

The README shows this command was used after running `build` to visualize all the replacements of constants throughout the html files that are generated after building.  However, this never works because the replacements happen during the build so `inject` detects no differences.

```
Modified files: []
Modified files for kusama/polkadot difference: []
```

Long story short, I think we could have just scrapped the `inject` command as it appears to be a legacy feature.  I am going to merge this PR because it has already been reviewed and is pretty big.  I will file a separate issue and follow-up with a smaller PR that just removes the stale code.

2022-07-05 19:20 UTC, merged