Remove ambiguity with precision
w3f/polkadot-wiki pull request #3567
Opened 2022-07-23 12:18 UTC by DrW3RK

2022-07-23 12:36 UTC, DrW3RK commented
The rendering as of now
<img width="736" alt="image" src="https://user-images.githubusercontent.com/86818441/180604927-6420759b-2721-4dbd-9d39-d5ca18edc7e1.png">

With this PR

<img width="711" alt="image" src="https://user-images.githubusercontent.com/86818441/180604883-5dcd71b6-7afd-4de7-9a66-acd37045b0f9.png">

While reviewing, check a few other pages on Polkadot Wiki and Kusama Guide to ensure nothing fuzzy is happening. Thanks!

2022-07-25 14:19 UTC, alfarok commented on components/RPC-Connection.jsx
>  			// TODO: this legacy function needs some attention (see https://github.com/w3f/polkadot-wiki/issues/3539)
```suggestion
```

2022-07-25 14:20 UTC, alfarok commented on components/RPC-Connection.jsx
> +				value = `${(value / values[network].precision)} ${values[network].symbol}`;
```suggestion
				value = `${value / values[network].precision} ${values[network].symbol}`;
```

2022-07-25 14:23 UTC, alfarok requested changes
Tested on several pages and works as expected:
![image](https://user-images.githubusercontent.com/13341935/180799650-b8f0d68f-745c-461d-bfd0-b4bbd20ce30f.png)

Very minor changes suggested, nothing that impacts the rounding logic.

2022-07-25 14:54 UTC, DrW3RK commented
Thanks! Please approve for merging

2022-07-25 15:45 UTC, alfarok approved these changes

2022-07-25 15:45 UTC, merged