Add jest testing to CI
w3f/polkadot-wiki pull request #3576
Opened 2022-07-26 02:24 UTC by alfarok

This PR addresses #3574.

work-in-progress

2022-07-27 00:04 UTC, alfarok commented on components/RPC-Connection.jsx
> +					setReturnValue(newValue);
This was actually causing an edge case where some 'const' values without filters were always using the default value even though a value was successfully being retrieved from the chain.  I thought the test framework wasn't working at first but it turned out the test was correct.  Unit testing already paying off. :partying_face:

2022-07-27 00:05 UTC, alfarok commented on package.json
> +    "@polkadot/util": "10.1.1",
All these dependencies should align in version

2022-07-27 00:06 UTC, alfarok commented on tests/rpc.test.js
> +});
I want to try loading the entire app and write more generic tests that can potentially find errors in the docs, but I will attempt that in another PR.

2022-07-28 12:09 UTC, DrW3RK approved these changes

2022-07-28 12:18 UTC, DrW3RK requested changes
holding this from merging. Please check why this fails

2022-07-28 17:31 UTC, alfarok commented
The tests are passing again with no changes.  This makes me think that it is timing related with the delay to receive the RPC response.  I am going to **bump the timeout from 2 seconds to 5 seconds** to see if that helps.  The tests will still complete faster than that if the data is available but wait a little longer if it's not yet.

If any of the tests prove to be more annoying that useful with intermittent failures we can remove or adjust further accordingly.

2022-07-28 17:34 UTC, DrW3RK commented
Makes sense. We can merge now

2022-07-28 17:34 UTC, DrW3RK approved these changes

2022-07-28 17:34 UTC, merged

2022-07-28 17:38 UTC, alfarok commented
I didn't push the change yet haha but I'll open in a new PR since it's minimal.