Update mirrors and deps
w3f/polkadot-wiki pull request #360
Opened 2020-04-03 09:08 UTC by Swader

Just an update.

2020-04-03 09:55 UTC, laboon requested changes
Looks like you caught some of the stuff from my earlier PR in here, rebasing should make it go away

2020-04-03 09:55 UTC, laboon commented on docs/mirror-learn-governance.md
> +Polkadot introduces a concept "Adaptive Quorum Biasing", which functions as a lever that the
```suggestion
Polkadot introduces the concept of "Adaptive Quorum Biasing", which functions as a lever that the
```

2020-04-03 09:55 UTC, laboon commented on docs/mirror-learn-governance.md
> +of seats (envisioned to be 24 for Polkadot) and all members have a fixed term (12 months).
```suggestion
of seats and all members have a fixed term (12 months).
```

This is redundant with the sentence before it.

2020-04-03 09:55 UTC, laboon commented on docs/mirror-maintain-guides-how-to-nominate-kusama.md
> +Select them, confirm the transaction, and you're done - you are now nominating.  Your nominations will become active in the next era.  Eras last four hours on Kusama - depending on when you do this,
```suggestion
Select them, confirm the transaction, and you're done - you are now nominating.  Your nominations will become active in the next era.  Eras last six hours on Kusama - depending on when you do this, your nominations may become active almost immediately, or you may have to wait almost the entire six hours before your nominations are active.  You can check how far along Kusama is in the current era on the [Staking page](https://polkadot.js.org/apps/#/staking).
```

2020-04-03 10:00 UTC, Swader commented
Should be good now

2020-04-03 11:47 UTC, lsaether commented
Do we need to update mirrors with PRs or does it do in the build process now?

2020-04-03 16:09 UTC, Swader commented
It is not in the build process yet, for now it's still manual. Optimally, the author of a change would run mirror.js before committing.

2020-04-06 12:34 UTC, lsaether commented
Ok we can track that here #366

2020-04-06 12:37 UTC, lsaether commented
It still looks like Bill's comments weren't addresses, at least I don't see "outdated" in the header so I assume this PR still built the old versions?

2020-04-21 15:25 UTC, lsaether commented
outdated after #389

2020-04-21 15:25 UTC, closed without merging