Kusama society rules link update
w3f/polkadot-wiki pull request #3647
Opened 2022-08-16 08:11 UTC by filippoweb3

Fixed bug in a link to Kusama society rules

2022-08-16 12:00 UTC, laboon requested changes
minor changes

2022-08-16 12:00 UTC, laboon commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +In order to decode the rules you need to navigate to the Parameters section: Element 1 ("proposal")
I would reword this to something like:

"The rules are encoded on-chain in UTF-8 format. This is displayed in most block explorers as a hexadecimal string. In order to see the rules in human-readable format, you can convert it. View the value Element 1.... etc. of the extrinsic's parameters, and copy the value corresponding to the key "Value". You can use a hex-to-UTF8 converter to then display the text. Note that the text is formatted with Markdown."

2022-08-16 12:00 UTC, laboon commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +  https://polkascan.io/pre/kusama/transaction/0x948d3a4378914341dc7af9220a4c73acb2b3f72a70f14ee8089799da16d94c17
This link doesn't work either =(

```suggestion
  https://kusama.subscan.io/extrinsic/0x948d3a4378914341dc7af9220a4c73acb2b3f72a70f14ee8089799da16d94c17
```

2022-08-16 12:17 UTC, filippoweb3 commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +In order to decode the rules you need to navigate to the Parameters section: Element 1 ("proposal")
Added as requested.

2022-08-17 11:16 UTC, laboon approved these changes
lgtm

2022-08-17 11:20 UTC, merged