Migration of account generation page to support pages
w3f/polkadot-wiki pull request #3676
Opened 2022-08-22 09:32 UTC by filippoweb3

Left some tiny intro and a list of ways to create accounts with links to support pages

2022-08-22 11:34 UTC, DrW3RK requested changes
I have some feedback that can help with future PRs as well.

1. It is important to ensure the content being deleted on the Wiki is present in the support article being referenced. 
2. It is okay to have redundant information on the Wiki page as well as the Support page. The ultimate goal is to have a coherent reading experience for the user

You have put a lot of effort to create the password reset section on the Wiki, but deleted it without ensuring it is transmitted to the support page. I tried to retain the backbone of this Wiki document with relevant references to the support articles. Let me know what you think from the perspective of a new reader landing on this Wiki page.

2022-08-22 11:34 UTC, profradha commented on docs/learn/learn-account-generation.md
> +address. The public and private parts together make up a Polkadot account. You can think about your public address like your mailbox and your private key like your key to open your mailbox. Everybody
I'm thinking if there are better words to to explain this than just saying public and private part.

Rephrased it a little bit. Feel free to edit it further

```suggestion
address. The public and private parts together make up a Polkadot account. You can think of the public address  of your account like your mailbox and the private key like the key to open that mailbox. Anybody can send mail to your mailbox, but only you can access them as only you have access to its key. In the context of Polkadot accounts,  anybody can send tokens to your public address but only you can transact with them using your private key. That is why you should keep your private key secret.
```

2022-08-22 11:48 UTC, filippoweb3 commented
I overlooked it and did not notice I deleted all that part I worked on! My apologies, I agree the page must be like you mentioned. I am going through it and check if it need further additions / rearrangements.

2022-08-23 09:38 UTC, DrW3RK approved these changes
Looks good. Made a few suggestions. Please address them and then we can merge this

2022-08-23 09:38 UTC, DrW3RK commented on docs/learn/learn-account-generation.md
> +- [Polkadot{.js} Browser Extension](#polkadot-js-apps) **RECOMMENDED FOR MOST USERS**
Have you mistakenly pointed this ref link to point to Polkadot JS Apps?

```suggestion
- [Polkadot-JS Browser Extension](#polkadot-js-browser-extension) **RECOMMENDED FOR MOST USERS**
```

2022-08-23 09:38 UTC, DrW3RK commented on docs/learn/learn-account-generation.md
>  separate local mechanism to generate your address and interact with Polkadot.
Staying consistent with Glossary https://support.polkadot.network/support/solutions/articles/65000110873-glossary and at the same time, preserving the link to this section referenced on third party websites
```suggestion
The Polkadot-JS Browser Extension (simply referred to as Polkadot Extension) provides a reasonable balance of security and usability. It provides a
separate local mechanism to generate your address and interact with Polkadot.
```

2022-08-23 09:38 UTC, DrW3RK commented on docs/learn/learn-account-generation.md
> +This method involves installing the Polkadot JS extension and using it as a “virtual vault," separate
```suggestion
This method involves installing the Polkadot Extension and using it as a “virtual vault," separate
```

2022-08-23 09:38 UTC, DrW3RK commented on docs/learn/learn-account-generation.md
> +:::info For the tutorial on how to create an account using Polkadot JS browser extension, visit [this support article](https://support.polkadot.network/support/solutions/articles/65000098878-how-to-c
```suggestion
:::info For the tutorial on how to create an account using Polkadot Extension, visit [this support article](https://support.polkadot.network/support/solutions/articles/65000098878-how-to-create-a-dot-account). 
```

2022-08-23 09:38 UTC, DrW3RK commented on docs/learn/learn-account-generation.md
Reasoning behind the recommendation 

```suggestion

Your address' format is only visual - the data used to derive this representation of your address
are the same, so you can use the same address on multiple chains. However, for privacy reasons, we
recommend creating a new address for each chain you're using.
```

2022-08-23 09:48 UTC, merged