Run "prettier" on all files in docs directory to achieve baseline state
w3f/polkadot-wiki pull request #3790
Opened 2022-09-14 20:18 UTC by alfarok

This PR runs `npx prettier --write .` in the `/docs` sub-directory, which applies the same rules as `npx pretty-quick` but to unmodified files to achieve a baseline state.  This should ensure small PRs that run `npx pretty-quick` as a final step will not introduce large GitHub diffs, complicating what should be a simple review.  As long as we keep up with running the command with new PRs this should be a one-time effort.

2022-09-15 09:23 UTC, DrW3RK requested changes

2022-09-15 09:23 UTC, DrW3RK commented on docs/learn/learn-governance.md
> +"./../../components/Voluntary-Locking"
This threw an error when rendering locally

```suggestion
import RPC from "./../../components/RPC-Connection" 
import VLTable from "./../../components/Voluntary-Locking"
```

2022-09-15 09:28 UTC, DrW3RK approved these changes
Apart from the RPC component issue (already fixeed), the rendering in all the changed docs looks good to me. Did a quick skim through.

2022-09-16 12:01 UTC, filippoweb3 approved these changes
Looks good to me :)

2022-09-18 22:49 UTC, merged