Reorg Ledger Page & Addition DevApp Installation Guidelines
w3f/polkadot-wiki pull request #4036
Opened 2022-11-10 10:18 UTC by filippoweb3

2022-11-11 10:52 UTC, filippoweb3 commented
hey @emresurmeli let me know what you think about this PR ;)

2022-11-21 12:58 UTC, DrW3RK requested changes
Looks good. Some minor suggestions.

2022-11-21 12:58 UTC, DrW3RK commented on docs/general/ledger.md
> +for single calls (i.e. bonding and nominating).
```suggestion
Ledger does not currently support batch calls; As a consequence, if you stake using the
[staking dashboard](https://staking.polkadot.network/#/overview), you must use a hot wallet.
Alternatively, you can use the [Polkadot-JS UI](https://polkadot.js.org/apps/#/explorer) that allows
for single calls (i.e., bonding and nominating).
```

2022-11-21 12:58 UTC, DrW3RK commented on docs/general/ledger.md
> +These instructions are for development installation only. It is recommended to install the
```suggestion
This section is for developers only. It is recommended to install the
```

2022-11-21 12:58 UTC, DrW3RK commented on docs/general/ledger.md
> +audit, you can install the developer release from the shell using the latest version published on
Zondax may update the apps even when there is no runtime upgrade on the network (like some of the backlogged feature requests). Rephrased the content a bit to reflect that.
Please accept this suggestion if the rephrased content captures the original intent.

```suggestion
Ledger apps for the Polkadot and Kusama ecosystems are developed by [Zondax](https://zondax.ch/).
When new functionalities are added to the Ledger apps, they are made available on a developer release for testing purposes. After a successful audit and review, the apps would be available for download and
installation using [Ledger Live](https://www.ledger.com/ledger-live). As it takes some
time for Ledger to audit and review the release, the app upgrade option may not be 
available on Ledger Live when the new runtime is deployed on the network. If this happens, users cannot use Ledger
devices with the Polkadot-JS UI, and while signing for a transaction, they will most likely
incur the error message "txn version not supported". Please do not panic if this happens, as there
are solutions to this problem. If you cannot wait a couple of days until the app passes the Ledger
audit, you can install the developer release from the shell using the latest version published on
```

2022-11-21 14:26 UTC, filippoweb3 commented
@DrW3RK thanks for the review! When you approve it, please do not merge as I will add a short video showing how to install the dev version of the app. I will do a final check before merging.

2022-11-21 15:46 UTC, DrW3RK commented
Got it! I'll review again after you add the mentioned contents

2022-11-22 15:13 UTC, filippoweb3 commented
@DrW3RK this is good to go. Tutorial added. Regarding the batch transfer calls implementation, I will create an issue to update all relevant pages in the wiki.

2022-11-23 07:37 UTC, DrW3RK approved these changes

2022-11-23 07:37 UTC, merged