Addition Section "Network Providers" on the Staking Page
w3f/polkadot-wiki pull request #4063
Opened 2022-11-18 14:37 UTC by filippoweb3

See linked issue.

2022-11-18 15:18 UTC, filippoweb3 commented
@DrW3RK added some info, not sure if I am going too far and if I am allowed to mention everything in the paragraph. Let me know what you think.

2022-11-24 12:41 UTC, DrW3RK requested changes
Thanks for taking the initiative for adding this to the Staking doc. A very important piece of info in the benefit of nominators. Polishing the writeup a bit by providing links to the relevant docs in the Wiki. Also, slashing due to unresponsiveness is ceiled at 7% and it does not result in the entire stake being confiscated. Probably better to back the Solana/Hetzner incident with an article from a reliable source or leave out mentioning them altogether.

2022-11-24 12:41 UTC, profradha commented on docs/learn/learn-staking.md
> +Most validator nodes run on cloud service providers that guarantee high hardware specifications and all safety measures in the case, for example, there is a shortage in power supply. Keep in mind tha
```suggestion

For successful operation, a Validator node should always be ensured to meet the required [software, hardware, and network bandwidth specifications](../maintain/maintain-guides-how-to-validate-polkadot#reference-hardware). 
Understandably, most of the validator nodes run on cloud service providers that guarantee high hardware specifications and high levels of availability and connectivity. Keep in mind that a validator in the active set is supposed to be fully online and available for producing blocks. If the active validator node goes offline due to network interruptions or a power outage, that validator might be subject to [slashing due to unresponsiveness](learn-staking-advanced#unresponsiveness). As [Polkadot's block production mechanism] is reasonably resilient to a small proportion of validators going offline, no slashing is imposed until 10% of the validators in the active set go offline. Hence, if multiple nodes are running on a single cloud service provider and go offline simultaneously due to an outage or due to a change in their terms and conditions policy regarding the support of Proof-of-Stake (PoS) operations, the offline validators and all the nominators backing them can be slashed up 7% of their stake on Polkadot.
```

2022-11-24 12:41 UTC, profradha commented on docs/learn/learn-staking.md
> +However, cloud services might not support Proof-of-Stake (PoS) operations in their Terms and Conditions Policy, depending on the country they are based in. In the case of conflict between the provide
Removing this section
```suggestion
```

2022-11-24 12:41 UTC, profradha commented on docs/learn/learn-staking.md
> +You must check if your nominations use cloud service providers that allow for Proof-of-Stake operations. You can contact them via email providers, and they should get back to you with more informatio
```suggestion
Hence, it is recommended that you check if you are nominating the validator nodes that are running on cloud service providers, and if they do, check if they allow for Proof-of-Stake operations. 

:::tip

You can connect your stash account to the [Polkawatch app](https://polkawatch.app/). The app will show your rewards earned in the past 60 eras divided by network provider and country. You will be able to see networks used by each validator and verify if your validators are using providers who support PoS. This is also a great tool to explore how decentralized your nominations are and act accordingly.

:::

```

2022-11-25 12:40 UTC, filippoweb3 commented
@DrW3RK thanks for checking this paragraph! I added some minor edits.

2022-11-25 13:47 UTC, DrW3RK approved these changes

2022-11-25 13:47 UTC, merged