Additions Parachains Host Implementers Guide
w3f/polkadot-wiki pull request #4200
Opened 2022-12-16 15:43 UTC by filippoweb3

- [ ] Add Validator info
- [ ] Add Nominator info
- [ ] Add Collator info

2022-12-19 16:44 UTC, filippoweb3 commented
@DrW3RK @alfarok I request some preliminary review on this PR. Let me know what you think!

2022-12-20 15:02 UTC, alfarok requested changes
Added some minor suggestions to review.  In general I would be careful using the link format where all links are provided at the end of the document.  The url audit tool isn't familiar with this format and prettier doesn't seem to respect the structure.  Even if the formatting is okay now another change made by someone else could cause it to split down the line.

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-parachains.md
> +{{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} includes a blockchain called relay
```suggestion
{{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} includes a blockchain called a relay
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-parachains.md
> +  defines the state-transition logic of the chain. The Runtime logic is divided into:
should both of these `state transition`'s be hyphenated or not not hyphenated?  I am not sure which one is more correct

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-parachains.md
> +    - Entry point are the means by which new information is introduced to a module and can limit the
```suggestion
    - The entry point defines the means by which new information is introduced to a module and can limit the
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-parachains.md
> +  - [Utility subsystem][]
I know this linking format is used in a few places already in the docs but I don't think these will be checked by the url auditing tool.  Not a big deal just something to be aware of.  I am not sure if this formatting is native to markdown or docsaurus specifically.

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +Validators also participate to the so-called **availability distribution**. In fact, once the
```suggestion
Validators also contribute to the so-called **availability distribution**. In fact, once the
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +Validators also participate to the so-called [**approval process**](#approval-process). Once the
```suggestion
Validators also participate in the the so-called [**approval process**](#approval-process). Once the
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +para-validators are a small subset of all validators, there a risk that by chance the majority of
```suggestion
para-validators are a small subset of all validators, there is a risk that by chance the majority of
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +approved. A rely-chain block containing a bad parablock must be reverted, while a relay-chain block
```suggestion
sense to think of relay-chain blocks as having been approvead instead of parablocks that have been
approved. A relay-chain block containing a bad parablock must be reverted, while a relay-chain block
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +  notices][] are gossiped among nodes so that all validators know which validators should check
If a link in this format is forced into a newline by prettier (due to spaces in the naming) does it cause the link to break?  From the syntax highlighting here I would this `Assignment notices` link is broken.

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +  postponement][]).
same as above here

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +backed blocks that are not included. To ensure nothing invalid end up in the finalized relay chain
```suggestion
backed blocks that are not included. To ensure nothing invalid ends up in the finalized relay chain
```

2022-12-20 15:02 UTC, alfarok commented on docs/learn/learn-validator.md
> +needs to distribute and invalid block to honest validators. Scenarios leading to a dispute can be
```suggestion
A dispute stems from a disagreement between two or more validators. For this to happen, a bad actor
needs to distribute an invalid block to honest validators. Scenarios leading to a dispute can be
```

2022-12-21 08:22 UTC, filippoweb3 commented
@alfarok should I add all the links within the text as usual using urls and remove all the ones at the end of the file (i.e. those with [subject][])? I tried to run prettier and it does not seem to mess up with the text. Let me know what you think is the best way to proceed here.

2022-12-21 14:37 UTC, alfarok commented
@filippoweb3 If you can it would be good to swap all them but I can also do it in a follow up PR if you don't have time to address it before the holiday.  

Even if prettier doesn't make any changes now, if someone adds even just one word in the future it could cause the line formatting to change and break a link.  I already noticed to happening a bunch in legacy links that use this formatting [here](https://github.com/w3f/polkadot-wiki/pull/4210)

It's just something that will be hard to notice when it happens which is why I think swapping to the other format, which we know will never change, is the better option.

2022-12-21 17:04 UTC, filippoweb3 commented
@alfarok I put everything within the text and deleted the links at the end of the doc ;)

2022-12-21 17:06 UTC, alfarok approved these changes
Thanks @filippoweb3 for updating the links, the repo should be free of this formatting now.  Apologies I didn't  notice this formatting behavior previously

2022-12-21 17:09 UTC, merged