Bridges re-write
w3f/polkadot-wiki pull request #426
Opened 2020-05-04 06:18 UTC by lsaether

closes #194 #160

2020-05-07 18:02 UTC, Swader requested changes

2020-05-07 18:02 UTC, Swader commented on docs/learn-bridges.md
> +diverse chain to communicate with each other. Bridge designs come in a variety
```suggestion
diverse chains to communicate with each other. Bridge designs come in a variety
```

2020-05-07 18:02 UTC, Swader commented on docs/learn-bridges.md
> +A parachain
Was this a draft paragraph you wanted to remove?

2020-05-07 18:02 UTC, Swader commented on docs/learn-bridges.md
> +of those should be able to be bridged directly to Polkadot without the need of
```suggestion
of those should be able to bridge directly to Polkadot without the need of 
```

Prefer active.

2020-05-07 18:02 UTC, Swader commented on docs/learn-bridges.md
> +`side`. Ether deposited into the contract on `main` generate a balance
```suggestion
`side`. Ether deposited into the contract on `main` generates a balance 
```

2020-05-07 18:02 UTC, Swader commented on docs/learn-bridges.md
> +- The XCLAIM component that maintains all accounts that own PolkadBTC.
```suggestion
- The XCLAIM component that maintains all accounts that own PolkaBTC.
```

2020-05-07 18:02 UTC, Swader commented on docs/learn-bridges.md
>  ## Resources
Do we maybe want to end with a CTA for teams to apply for grants if they want to build bridges?

2020-05-11 10:10 UTC, lsaether commented on docs/learn-bridges.md
>  ## Resources
good idea

2020-05-11 11:35 UTC, merged