Additional information on system chains and collectives
w3f/polkadot-wiki pull request #4263
Opened 2023-01-04 18:24 UTC by alfarok

This PR addresses #4094, originating from #4261 with the new changes and re-org from #4262

- [x] Cleanup pass over legacy learn-common-good-chains doc
- [x] Add some additional info on Collectives
- [x] Elaborate on how parachains impact bridging

2023-01-04 18:25 UTC, alfarok commented
Replacing w/ #4261 after the re-org and updates from #4262.

2023-01-11 13:10 UTC, DrW3RK requested changes
Looks good. Minor changes requested.

2023-01-11 13:10 UTC, DrW3RK commented on docs/learn/learn-system-chains.md
> +other parachains, so a bridge hub can support bridges to many other consensus systems.
Removing the ambiguous statement. The activity on parachain does affect the relaychain and other parachains (through XCM). Probably the sentence can benefit from rephrasing or be removed completely. 

```suggestion
isolation provided by parachains.
```

2023-01-11 14:39 UTC, alfarok commented
Thanks @DrW3RK, suggestion applied!

2023-01-11 14:44 UTC, DrW3RK approved these changes

2023-01-11 14:44 UTC, merged