Add new definitions to glossary & replace Gov2 with OpenGov
w3f/polkadot-wiki pull request #4264
Opened 2023-01-04 22:25 UTC by alfarok

This PR addresses the initial scope of #4258 adding the following definitions to the glossary doc:

- [x] OpenGov
- [x] Fellowship
- [x] Collectives
- [x] Whitelist Pallet
- [x] Polkadot Alliance
- [x] Tracks

and replaces the original `Gov2` phrasing with `OpenGov` in several locations.

2023-01-05 21:34 UTC, DrW3RK requested changes
Some minor fixes requested.

2023-01-05 21:34 UTC, DrW3RK commented on docs/general/glossary.md
> +the members (weighted by their rank) constitutes the Fellowship's considered opinion.
Brevity is important in Glossary. When the respective sections are ready, we can link to them here

```suggestion
A mostly self-governing expert body with a primary goal of representing humans who embody and
contain the technical knowledge base of the Kusama and/or Polkadot networks and protocols.
```

2023-01-05 21:34 UTC, DrW3RK commented on docs/general/glossary.md
> +in a democratic manner.
Please check of the markdown link works

```suggestion
Previously known as Governance v2 (Gov2) during early development, [OpenGov](../learn/learn-opengov) serves as the current
governance protocol for Kusama and will eventually be deployed on Polkadot. 
```

2023-01-05 21:34 UTC, DrW3RK commented on docs/general/glossary.md
> +development standards and expose bad actors within the ecosystems of Polkadot.
Avoid mention of "Top projects" or any form of bias in the Wiki documentation

```suggestion
The
Polkadot Alliance is an [on-chain collective](#collectives) founded by Acala, Astar, Interlay, Kilt, Moonbeam, Phala, and Subscan, to establish standards and ethics for
open-source development in [referendum #94](https://polkadot.polkassembly.io/referendum/94). It aims to support
development standards and expose bad actors within the ecosystems of Polkadot.
```

2023-01-05 21:34 UTC, DrW3RK commented on docs/general/glossary.md
> +with a Track. The Track outlines the lifecycle for the proposal and is independent from other
Please check if the markdown link works

```suggestion
with a [Track](../maintain/maintain-guides-opengov#origins-and-tracks). The Track outlines the lifecycle for the proposal and is independent from other
```

2023-01-05 23:55 UTC, alfarok commented
> Some minor fixes requested.

Thanks for the suggestions, committed and ran a link audit to make sure nothing was broken.  Should be good for another look whenever you get a free moment.

2023-01-06 14:49 UTC, DrW3RK approved these changes
Fixed a markdown link. Looks good now! Please confirm and merge.

2023-01-06 15:03 UTC, merged