Reorg Nominator Page
w3f/polkadot-wiki pull request #4418
Opened 2023-02-02 10:21 UTC by filippoweb3

See [this issue](https://github.com/w3f/polkadot-wiki/issues/4376) and [this google doc](https://docs.google.com/document/d/1Fl8ReBIzcaQEOyF6s03d7MEcgk8aTVEt7xjmzAk_k5I/edit) for more information about the Wiki reorg.

2023-03-07 13:23 UTC, DrW3RK requested changes

2023-03-07 13:23 UTC, DrW3RK commented on docs/learn/learn-nominator.md
> +## Why Nominating?
```suggestion
## Why Nominate?
```

2023-03-07 13:23 UTC, DrW3RK commented on docs/learn/learn-nominator.md
> +- You become part of the {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} Movement, a
```suggestion
- You become part of the {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} movement, a
```

2023-03-07 13:23 UTC, DrW3RK commented on docs/learn/learn-nominator.md
> +  Internet, Web 3.0: a decentralized, privacy-focused, and trustless internet.
```suggestion
  Internet, Web3: a decentralized, privacy-focused, and trustless internet.
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +  [crowdloans](./learn-crowdloans.md).
This statement can be rephrased as it has less to do with nominating DOT/KSM. You can't participate in crowdloans and take part in governance. What you could highlight is here is that "As a nominator securing the network, you can also use the nominated DOT/KSM to participate in Governance"

```suggestion
- You are an essential piece of the puzzle, keeping
  {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} secure, deciding the future
  direction of the project by voting in [OpenGov](./learn-opengov.md) and participating in parachain
  [crowdloans](./learn-crowdloans.md).
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +- You start to understand how {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} works
```suggestion
- You will start to understand how {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} works
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +  rewards, and build your reputation as a trusted nominator. If you need more than this, the next
```suggestion
  rewards, and build your reputation as a trusted nomination pool operator. If you like to be more involved, the next
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +  currency inflation as well.
```suggestion
- By getting [staking](./learn-staking.md) rewards you keep up with or (likely) stay ahead of 
  {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} inflation.
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +  group of professionals and enthusiasts around the world aspiring to build and foster the next-gen
```suggestion
  group of diverse professionals and enthusiasts around the world aspiring to build and foster the next-gen
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +transfer funds you want to use for staking. For these accounts, it is recommended a "cold solution"
```suggestion
transfer funds you want to use for staking. For these accounts, it is recommended to use a "cold wallet" solution 
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +account but use its economic power and sign staking-related transactions on behalf of it. This is
```suggestion
account but sign staking-related transactions on behalf of it. This is
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +metrics, followed by a brief description of each.
```suggestion
metrics shown as an example, followed by a brief description of each.
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +  number of bonded tokens). Note that nominating those with a higher yield does not guarantee
```suggestion
  number of bonded tokens). Note that nominating those with a higher yield may not guarantee
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +## Good Practices
```suggestion
## Good Nominator Practices
```

2023-03-07 13:23 UTC, profradha commented on docs/learn/learn-nominator.md
> +vary over time. You can read the blog post
```suggestion
Finally, if you have a minimal amount of DOTs close to the value of `minActiveNomination`, you may need to stake more DOT to get into
the election set. The nominator-to-validator mapping solution needs to be evaluated within a single block duration, and if there are
too many nominators, the lowest-staked nominations will be dropped from even being considered to be part of the electing set. This `minActiveNomination` value is dynamic and will
vary over time. You can read the blog post
```

2023-03-10 14:54 UTC, filippoweb3 commented
hey @DrW3RK let me know if you have any additional feedback about this PR ;)

2023-03-10 15:09 UTC, DrW3RK approved these changes

2023-03-10 15:10 UTC, DrW3RK commented
Good to go!

2023-03-10 15:10 UTC, merged