Polkadot nominator and validator guides
w3f/polkadot-wiki pull request #467
Opened 2020-05-19 13:03 UTC by lsaether

2020-05-22 11:03 UTC, wpank requested changes

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-kusama.md
> +identities, the amount of DOTs that are staking for them, amount that is their own provided stake,
```suggestion
identities, the amount of KSM that are staking for them, amount that is their own provided stake,
```

This is for the Kusama section, right? (or at least that's what the filename implies.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-kusama.md
> +stay in the waiting queue until they have enough DOTs backing them (as allocated through the
```suggestion
stay in the waiting queue until they have enough KSM backing them (as allocated through the
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-kusama.md
> +Phragmen election mechanism). It is possible validator can remain in the queue for a very long time
```suggestion
[Phragmen election mechanism](https://wiki.polkadot.network/docs/en/learn-phragmen)). It is possible validator can remain in the queue for a very long time
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-kusama.md
> +The "Targets" subsection ([link](https://polkadot.js.org/apps/#/staking/targets)) will help you
Would list them in order of:

1. Account Actions
2. Payouts
3. Targets

As this is the order they appear in on the UI

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-kusama.md
> +to stake and nominate.
```suggestion
to stake and nominate. Note, this tab will only show up when you have existing accounts in the [accounts](https://polkadot.js.org/apps/#/accounts) page.
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-kusama.md
> +validator.
Would reword this for more detail:

The "Validator Stat's subsection ([link](https://polkadot.js.org/apps/#/staking/query)) allows you to query a validator's stash address and see historical charts on era points, elected stake, rewards, and slashes.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +While the [validators][] are active participants in the network that take part in the block
Link to validator page

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +production and finality mechanisms, nominators take a more passive role that can compared to the
```suggestion
production and finality mechanisms, nominators take a more passive role with a
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +worrying about online uptime. However, a good nominator performs diligence on the validators that it
```suggestion
worrying about online uptime. However, a good nominator performs diligence on the validators that they
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +elects. When looking for validators to nominate, a nominator should pay attention to its own reward
```suggestion
elect. When looking for validators to nominate, a nominator should pay attention to their own reward
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +percentage for nominating a specific validator - as well as the risk that it bares of being slashed
```suggestion
percentage for nominating a specific validator - as well as the risk that they bare of being slashed
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +Nominators are recommended to set up two separate stash and controller accounts. Explanation and
```suggestion
Nominators are recommended to set up separate stash and controller accounts. Explanation and
```
The two here kind of sounds like they need two stash and two controller accounts

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +
Would maybe add a note here that this will be applicable when NPoS change happens. There's a disclaimer at the beginning, but also adding a brief one here wouldn't hurt.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +validator.
Would copy the changes from above into here as well.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +
Would add a note here that although you can nominate all 16, the stake will be dispersed via phragmen, and you may not actually actively nominate all the ones you choose.

2020-05-22 11:03 UTC, wpank commented on website/sidebars.json
> +          "maintain-guides-how-to-nominate-polkadot",
These should be added in addition, not changing this line. (There should be both pages on kusama and polkadot)

2020-05-22 11:03 UTC, wpank commented on website/sidebars.json
> +          "maintain-guides-how-to-validate-polkadot",
Same as above, this should be an addition, not a change.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +id: maintain-guides-how-to-validate-kusama
```suggestion
id: maintain-guides-how-to-validate-polkadot
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +title: Run a Validator (Kusama)
```suggestion
title: Run a Validator (Polkadot)
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Web3 Foundation forum](https://forum.web3.foundation/).
I heard word of deprecating the discourse forums - nothing really happens here. Is this worth mentioning?

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +```
This will change, but not really sure what it will look like in the meantime.....

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +> **Note:** Validators must sync their nodes in archive mode to avoid being slashed. If you've
I think this can change a bit - validators won't be slashed, but their nodes just won't start (which can mean slashing).

**Note:** If a Validator syncs as a full node, they must sync their nodes in archive mode, otherwise the node will throw an error when on start.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +
There should be something here on rocksdb vs paritydb - right now people should use rocksdb, but paritydb will be faster and eventually we will switch to that. If you use one vs the other it will require a resync.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +> **Note:** If you do not already have KSM, this is as far as you will be able to go until the end
```suggestion
> **Note:** If you do not already have DOTs, this is as far as you will be able to go until the end
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +> KSM to continue, as balance transfers are disabled during the soft launch. Please keep in mind
```suggestion
> DOTs to continue, as balance transfers are disabled during the soft launch. Please keep in mind
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +> that even for those with KSM, they will only be indicating their _intent_ to validate; they will
```suggestion
> that even for those with DOTs, they will only be indicating their _intent_ to validate; they will
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +## Bond KSM
```suggestion
## Bond DOTs
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +Make sure not to bond all your KSM balance since you will be unable to pay transaction fees from
```suggestion
Make sure not to bond all your DOT balance since you will be unable to pay transaction fees from
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +- Bond the KSM of the Stash account. These KSM will be put at stake for the security of the network
```suggestion
- Bond the DOTs of the Stash account. These DOTs will be put at stake for the security of the network
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +- **Stash account** - Select your Stash account. In this example, we will bond 100 milliKSMs - make
```suggestion
- **Stash account** - Select your Stash account. In this example, we will bond 100 milliDOTs - make
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +  need a small amount of KSM in order to start and stop validating.
```suggestion
  need a small amount of DOTs in order to start and stop validating.
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +- **Value bonded** - How much KSM from the Stash account you want to bond/stake. Note that you do
```suggestion
- **Value bonded** - How much DOts from the Stash account you want to bond/stake. Note that you do
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +  not need to bond all of the KSM in that account. Also note that you can always bond _more_ KSM
```suggestion
  not need to bond all of the DOTs in that account. Also note that you can always bond _more_ DOTs
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +./target/release/polkadot --validator --name "name on telemetry" --unsafe-rpc-expose
```suggestion
./target/release/polkadot --validator --name "name on telemetry"
```

You shouldn't actually need the --unsafe-rpc-expose flag anymore, the addition of this initially was a bug.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +this flag only exposes RPC methods locally.
Can remove the note on the unsafe rpc methods.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +needed.
Remove mention of unsafe rpc.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Telemetry](https://telemetry.polkadot.io/#/Kusama) and find your node. Note that this will show all
Link should be polkadot telemetry

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +nodes on the Kusama network, which is why it is important to select a unique name!
```suggestion
nodes on the Polkadot network, which is why it is important to select a unique name!
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Kusama Validator chat](https://riot.im/app/#/room/#KusamaValidatorLounge:polkadot.builders).
Replace with Polkadot links.

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +validator set, you are now running a Kusama validator! If you need help, reach out on the
```suggestion
validator set, you are now running a Polkadot validator! If you need help, reach out on the
```

2020-05-22 11:03 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +$ docker run parity/polkadot:v0.7.28 --validator --name "name on telemetry"
```suggestion
$ docker run parity/polkadot:latest --validator --name "name on telemetry"
```

2020-05-27 09:43 UTC, lsaether commented on docs/maintain-guides-how-to-nominate-kusama.md
> +The "Targets" subsection ([link](https://polkadot.js.org/apps/#/staking/targets)) will help you
good point

2020-05-27 09:57 UTC, lsaether commented on website/sidebars.json
> +          "maintain-guides-how-to-nominate-polkadot",
I think it makes sense that the Polkadot wiki only displays the sidebar for the Polkadot guide and the Kusama guide shows the Kusama ones.

2020-05-27 10:05 UTC, lsaether commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Web3 Foundation forum](https://forum.web3.foundation/).
It doesn't get much attention. Probably opening up an issue on one of the relevant repositories on GitHub gets more visibility.

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-nominate-polkadot.md
> +worrying about online uptime. However, a good nominator performs diligence on the validators that
```suggestion
worrying about online uptime. However, a good nominator performs due diligence on the validators that
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +code available in the **v0.7** branch.
```suggestion
code available in the **v0.8** branch.
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +You should generally use the latest **0.7.x** tag. At the time of writing, this was **0.7.28**, but
```suggestion
You should generally use the latest **0.8.x** tag. At the time of writing, this was **0.8.0**, but
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +you should review the output from the "git tag" command (`git tag | grep "$v\0\.7"`) to see a list
```suggestion
you should review the output from the "git tag" command (`git tag | grep "$v\0\.8"`) to see a list
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +of all the potential 0.7 releases. You should replace `v0.7.28` with the latest build (i.e., the
```suggestion
of all the potential 0.8 releases. You should replace `v0.8.0` with the latest build (i.e., the
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +git tag | grep "$v\0\.7"
```suggestion
git tag | grep "$v\0\.8"
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +git checkout v0.7.28
```suggestion
git checkout v0.8.0
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +> **Note:** Validators must sync their nodes in archive mode to avoid being slashed. If you've
Actually you do not need to run in archive mode, you can run in unsafe pruning mode with the following flags:

`--unsafe-pruning --pruning <pruning number>`

Where pruning number can be something like 16384

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +
Add a note here that until transfers are enabled, you _must_ use the same account if you did not get DOT injections done.

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +this flag only exposes RPC methods locally.
With the V0.8.0 release, the necessity of this was removed.

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Telemetry](https://telemetry.polkadot.io/#/Kusama) and find your node. Note that this will show all
```suggestion
[Telemetry](https://telemetry.polkadot.io/#list/Polkadot%20CC1) and find your node. Note that this will show all
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Kusama Validator chat](https://riot.im/app/#/room/#KusamaValidatorLounge:polkadot.builders).
```suggestion
[Polkadot Validator chat](https://matrix.to/#/!NZrbtteFeqYKCUGQtr:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=web3.foundation).
```

2020-05-27 10:24 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +[Kusama forum](https://forum.kusama.network/) or in the
```suggestion
[Web3 Foundation forum](https://forum.web3.foundation/) or in the
```

2020-05-27 10:31 UTC, wpank commented on docs/maintain-guides-how-to-validate-polkadot.md
> +> **Note:** Validators should sync using the RocksDb backend by passing the `--databse RocksDb`
```suggestion
> **Note:** Validators should sync using the RocksDb backend by passing the `--database RocksDb`
```

2020-05-27 10:32 UTC, wpank approved these changes

2020-05-27 10:57 UTC, merged