Update wallets.md
w3f/polkadot-wiki pull request #4713
Opened 2023-04-20 10:04 UTC by Dorreguinho

2023-04-21 12:35 UTC, filippoweb3 reviewed
thanks for proposing this addition. Although I can see the project received W3F funding, the app does not seem to be a wallet specific to the Polkadot/Kusama ecosystem, and IMO, the addition of this project to this page is not justified. I will pass this to @DrW3RK for final decision. Thanks for your understanding.

2023-04-25 16:51 UTC, Dorreguinho commented
Hi @filippoweb3, thanks for your comment! It's not specific because we have a multichain approach, but we're really interested in getting more and more involved with the Polkadot Ecosystem, for that reason the application.

Hope that we can overcome this. Btw, we're super interested in discussing some kind of collaboration or action to get more involved in the ecosystem.

Kind regards, Agustin.

2023-05-03 12:24 UTC, Dorreguinho commented
Hello @filippoweb3 & @DrW3RK, have you any update on this?

2023-05-03 21:47 UTC, DrW3RK commented
Hi @Dorreguinho, We are currently reviewing your wallet implementation. Please give us some additional time for this. 

We are excited that you want to be more involved in the Polkadot ecosystem. Could you please send an email to me at radha@web3.foundation and I will put you in touch with the relevant team!

2023-05-09 09:35 UTC, DrW3RK requested changes
I tested the wallet on iPhone and I see that the wallet allows for balance transfers and staking. Although, I do not see an option to choose a nomination pool. I see there are apps for participation on governance on other chains, but I do not see an app for Polkadot. Also, where can I see/interact with NFTs on my Polkadot wallet? 

Please let me know if I'm mistaken with my testing. Looking forward to your response! Also, is the wallet software open source?

2023-05-09 09:35 UTC, DrW3RK commented on docs/general/wallets.md
> +| [Citadel.one](https://app.citadel.one/)           | [iOS (Testflight)](apple.co/3PWc6s9), [Android](https://bit.ly/3N9ZtrH) | **Yes**, **Yes**             | **Yes** | **No**    | **Yes**        | Y
```suggestion
| [Citadel.one](https://app.citadel.one/)           | [iOS (Testflight)](apple.co/3PWc6s9), [Android](https://bit.ly/3N9ZtrH) | **Yes**, No            |  No  |  No    | **Yes**       | No         | [Citadel.one Features](#citadel-one)             |
```

2023-05-10 21:50 UTC, Dorreguinho commented
@DrW3RK Hello! You're right, I've a typo when I was completing the table. Thanks for your review!

Btw, I just sent you an email so you can put me in touch :)

Thanks again for your kindness!

2023-05-22 19:08 UTC, Dorreguinho commented
@DrW3RK Hey hope that you're doing well! 
I'd like to know some updates on this, also I sent you an email some weeks ago to get in contact with the foundation.

Thanks a lot! Have an awesome week :)

2023-06-20 14:26 UTC, DrW3RK commented
No plans to modify the wallets page to include closed source projects at this time.

2023-06-20 14:26 UTC, closed without merging