Wiki reorg: AnV Page & Parachain Protocol
w3f/polkadot-wiki pull request #4774
Opened 2023-05-08 09:31 UTC by filippoweb3

See [this issue](https://github.com/w3f/polkadot-wiki/issues/4376) and [this google doc](https://docs.google.com/document/d/1Fl8ReBIzcaQEOyF6s03d7MEcgk8aTVEt7xjmzAk_k5I/edit) for more information about the Wiki reorg.

2023-05-08 12:01 UTC, filippoweb3 commented
@DrW3RK @CrackTheCode016 let me know what you think. I think it is better to merge this first and then open a new PR to add the async backing. Sketches might change a bit in the future and we could think to split the page into smaller ones with the category "Parachain protocol".

2023-05-08 16:43 UTC, CrackTheCode016 requested changes
Looks overall good to me, a few small nits.  I think we could do a better job standardizing some of the language used, but the information seems sensible and correct.

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains-protocol.md
> +strong security guarantees. The Availability and Validity (AnV) Protocol essentially describes the
```suggestion
strong security guarantees. The Availability and Validity (AnV) Protocol describes the
```

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains-protocol.md
> +### AnV Protocol
```suggestion
### Availability and Validity (AnV) Protocol
```

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains-protocol.md
> +Parachain Protocol from another perspective (i.e. availability and validity; more about this later
```suggestion
Parachain Protocol from the perspective of availability and validity.
```

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains-protocol.md
> +:::info Parablocks vs Relay-Chain blocks
nit: 

```suggestion
:::info Parablocks vs. Relay Chain Blocks
```

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains.md
> +the {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} system. They
Just a small comment, we use the terms protocol-system-blockchain interchangeably - I wonder what the proper nomenclature is / we should be using?

I tend to like to use protocol, simply because I feel Polkadot is a protocol for parachains, but perhaps it isn't accurate.

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains-protocol.md
> +[Availability and Validity (AnV) chapter in **The Polkadot Protocol Specification**](https://spec.polkadot.network/#chapter-anv).
```suggestion
[Availability and Validity (AnV) chapter in **The Polkadot Protocol Specification**](https://spec.polkadot.network/chapter-anv).
```

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains.md
> +good analogy of a state with a light switch that can be either on or off. Each parachain has its own
```suggestion
good analogy of a state with a light switch that can be either on or off, which is one of the simplest examples of how a state machine functions. Each parachain has its own
```

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-parachains.md
> +become parathreads.
Link to parathreads here?

2023-05-08 16:43 UTC, CrackTheCode016 commented on docs/learn/learn-validator.md
> +[chain selection within GRANDPA](./learn-parachains-protocol.md/#chain-selection), ensuring that
```suggestion
[chain selection process within GRANDPA](./learn-parachains-protocol.md/#chain-selection), ensuring that
```

2023-05-11 10:56 UTC, DrW3RK approved these changes

2023-05-11 11:01 UTC, CrackTheCode016 approved these changes

2023-05-11 11:01 UTC, merged