Proper Learn Intro Page
w3f/polkadot-wiki pull request #4917
Opened 2023-06-16 14:09 UTC by CrackTheCode016

- Similar to `build-index` and `maintain-index`, add a section for learn-index
- Builds a starting point for the `Learn` section of the wiki
- Change all relevant links for `Learn` to start at `learn-index`

2023-06-18 06:39 UTC, filippoweb3 requested changes
@DrW3RK @CrackTheCode016 Added some suggestions. Although the page is beneficial, now that the wiki is under major reorg and sections and sidebar order might change, the page will likely create additional work. I recommend keeping this unmerged, but I also understand if you want to publish it and create PRs whenever the wiki changes.

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +title: Learn Polkadot
```suggestion
title: Learn about Polkadot
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +description: Learn how the Polkadot network works, from the ground up.
```suggestion
description: Learn how the Polkadot network works and what tool you can use to interact with it.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +blockchain.
```suggestion
Whether you are a developer or someone just getting started with
blockchain, here you will learn how the Polkadot network works from the ground up - from accounts to the protocols that power the Polkadot network.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +[find here](./learn-video-tutorials.md).
```suggestion
If you want to learn more about how to use different tools on Polkadot, you can visit the [Polkadot Technical Explainers playlist](https://youtube.com/playlist?list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8) on YouTube.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +[here](./learn-accounts).
```suggestion
Learn the basics of transactions, accounts, staking, NFTs, and more.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +[how-to guides for staking](./learn-staking-guides):
```suggestion
Learn more advanced concepts of the Polkadot network.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +Learn more about Polkadot's network architecture in depth:
```suggestion
Learn more about Polkadot's network architecture in depth.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +Learn how Polkadot compares to other similar technologies:
```suggestion
Learn how Polkadot compares to other similar technologies.
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +## Future Implementations & Upcoming Features
```suggestion
## Future Implementations
```

2023-06-18 06:39 UTC, filippoweb3 commented on docs/learn/learn-index.md
> +Learn upcoming innovations for the Polkadot network that are not yet released:
```suggestion
Learn about upcoming innovations for the Polkadot network that are not yet implemented.
```

2023-06-19 14:36 UTC, CrackTheCode016 commented
@filippoweb3 How much will it change this page you think? 

If it's just a matter of adding pages / re-ordering a few, I think it could be merged for now. What do you think?

2023-06-20 09:39 UTC, DrW3RK approved these changes
Looks good! Serves as an index page and makes sense to link to this doc when a wiki reader clicks on the "Learn" button. Owing to @filippoweb3 's concern, let us ensure that updates/additions/deletions to the learn section are tracked on this document as well.

2023-06-20 11:52 UTC, filippoweb3 approved these changes

2023-06-20 11:52 UTC, merged