Wiki Reorg: Unify Statemin* pages
w3f/polkadot-wiki pull request #4940
Opened 2023-06-22 08:51 UTC by filippoweb3

2023-06-22 13:27 UTC, DrW3RK requested changes

2023-06-22 13:27 UTC, DrW3RK commented on docs/learn/learn-assets.md
> +title: Polkadot Asset Hub
Can just be Asset Hub. Depending on whether it is on Polkadot Wiki or Kusama Guide, the readers can deduce that we are discussing about Asset Hub on the respective chains.

```suggestion
title: Asset Hub
```

2023-06-22 13:27 UTC, DrW3RK commented on docs/learn/learn-assets.md
>  {{ polkadot: Statemint, :polkadot }}{{ kusama: Statemine, :kusama }} as long as they can reserve the
```suggestion
Asset Hub as long as they can reserve the
```

2023-06-22 13:27 UTC, DrW3RK commented on kusama-guide/sidebars.js
> -                "general/kusama/kusama-statemine",
If you are changing these, then you have to implement redirects as well so the links on third party websites are not broken.

2023-06-22 13:29 UTC, DrW3RK commented on kusama-guide/sidebars.js
> -                "general/kusama/kusama-statemine",
I'm referring to 

                "learn/learn-staking-guides",
                "learn/learn-identity-guides",
                "learn/learn-assets-guides",
                "learn/learn-vault-guides",

2023-06-22 17:39 UTC, filippoweb3 commented
@DrW3RK I also fixed the broken links in the previous PR about wallets. There were also some major conflicts with the two previous PRs that now are resolved.

2023-06-23 09:21 UTC, DrW3RK approved these changes

2023-06-23 09:21 UTC, merged