Info banner controller accounts
w3f/polkadot-wiki pull request #5075
Opened 2023-08-02 15:03 UTC by filippoweb3

2023-08-02 15:04 UTC, filippoweb3 commented
@DrW3RK I also unlisted one video about controller accounts on the tech explainers playlist

2023-08-02 17:06 UTC, DrW3RK requested changes

2023-08-02 17:06 UTC, DrW3RK commented on docs/maintain/maintain-guides-how-to-validate-polkadot.md
The image in bond DOT section needs replacement as it shows controller account

<img width="839" alt="image" src="https://github.com/w3f/polkadot-wiki/assets/86818441/9a86ae98-9b82-44be-8dac-1ba937b4b4f6">

2023-08-04 14:23 UTC, filippoweb3 commented on docs/maintain/maintain-guides-how-to-validate-polkadot.md
@DrW3RK I updated the figures

2023-08-04 17:42 UTC, DrW3RK approved these changes
I found a few other instances on the Wiki where Controller accounts were mentioned. If possible, please do another check just to be sure. Approved to be merged.

2023-08-04 17:42 UTC, DrW3RK commented on docs/learn/learn-controller.md
> +[this discussion](https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748).
```suggestion
Controller accounts are deprecated. For more information, see
[this discussion](https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748).
```

2023-08-04 17:42 UTC, DrW3RK commented on docs/maintain/maintain-guides-how-to-validate-polkadot.md
> +[this discussion](https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748).
```suggestion
Controller accounts are deprecated. For more information, see
[this discussion](https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748).
```

2023-08-07 07:33 UTC, merged