Wireguard subsection added to systemd article in Wiki
w3f/polkadot-wiki pull request #518
Opened 2020-06-01 20:31 UTC by m-saxemberg

This PR was created with the fix for the issue #513 "Add Wireguard information to the "Using systemd for the Validator Node" section" shown here:
https://github.com/w3f/polkadot-wiki/issues/513

2020-06-02 14:50 UTC, Swader requested changes
Thank you! Just some minor changes

2020-06-02 14:50 UTC, Swader commented on docs/maintain-guides-how-to-systemd.md
> +## Wireguard systemd configuration for Validator - Sentries VPN.
```suggestion
## Wireguard systemd configuration
```

2020-06-02 14:50 UTC, Swader commented on docs/maintain-guides-how-to-systemd.md
> +You can also restart automatically your VPN configuration among validator and sentries using the configuration you have already created in the [Set Up a Sentry Node - Public Node](maintain-guides-how
```suggestion
You can automatically restart your VPN tunnel between your validator and its sentries using the configuration you have already created in the [Set Up a Sentry Node - Public Node](maintain-guides-how-to-setup-sentry-node) guide.
```

2020-06-02 14:50 UTC, Swader commented on docs/maintain-guides-how-to-systemd.md
> +Create a another unit file called `wireguard.service` in `/etc/systemd/system/`.
```suggestion
Create a file called `wireguard.service` in `/etc/systemd/system`.
```

2020-06-02 14:50 UTC, Swader commented on docs/maintain-guides-how-to-systemd.md
> +Then you will write the commands needed to start automatically the wireguard connection previously configured as `wg0` in the `wgo.conf` file under the `/etc/wireguard/` directory.
```suggestion
Write the commands needed to auto-start wireguard previously configured as `wg0` into the `wgo.conf` file in the `/etc/wireguard/` directory.
```

2020-06-02 14:50 UTC, Swader commented on docs/maintain-guides-how-to-systemd.md
> +The path to the wg-quick binary on Debian based distributions usually is: `/usr/bin/wg-quick`.
```suggestion
The path to the wg-quick binary on Debian based distributions is usually: `/usr/bin/wg-quick`. If in doubt, run `whereis wg-quick`.
```

2020-06-02 14:50 UTC, Swader commented on docs/maintain-guides-how-to-systemd.md
> +To enable this to autostart on bootup run:
```suggestion
To enable this to autostart on boot:
```

2020-06-02 15:53 UTC, m-saxemberg commented
All requested changes have been added

2020-06-03 09:06 UTC, Swader approved these changes
Very good,

now please just merge master to make our links-checker CI pass, run prettier on the file (`npx prettier --write`) to make our formatting CI pass, and we're good to go!

2020-06-03 15:20 UTC, lsaether approved these changes
Thanks!

EDIT: I'm not sure why the CI jobs didn't run on the last commit, but if you could run `prettier` on the page and push another commit (like bruno said above) then it will be good to merge.

2020-06-03 17:30 UTC, m-saxemberg commented
I'm not sure why it didn't run the tests before. 
The following prettier command was run
npx prettier --write maintain-guides-how-to-systemd.md
maintain-guides-how-to-systemd.md 162ms

2020-06-03 17:35 UTC, lsaether commented
Still failing - but because of a different file that's not your fault. It will be fixed in another PR so I'll merge this first.

2020-06-03 17:35 UTC, merged