Add Bounty Context to Treasury Page
w3f/polkadot-wiki pull request #5307
Opened 2023-10-26 08:39 UTC by filippoweb3

- added banner to guides

2023-10-30 13:44 UTC, anaelleparity requested changes
Part 1/2 of the review process.

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-guides-bounties.md
> +information. When a user submits a bounty spending proposal, they will need to find an off-chain way
```suggestion
information. When a user submits a bounty spending proposal, they will need to find an off-chain medium
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-guides-bounties.md
> +to explain the proposal through for example [Polkassembly](https://polkadot.polkassembly.io/opengov)
```suggestion
to explain the proposal, for example a bounty proposal document on Polkassembly [Polkassembly](https://polkadot.polkassembly.io/opengov)
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-guides-bounties.md
> +can help as a checklist of all needed information for OpenGov voters to make an informed decision.
```suggestion
can be used to submit all the information needed by OpenGov voters to make an informed decision.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +referendum, can be a long and uncertain process. This can be unideal, for example, for events'
```suggestion
referendum, can be a long and uncertain process. This is not always a suitable option, for example, for events'
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +[child bounties](#child-bounties) (that is why bounties are also called _parent_ bounties).
```suggestion
[child bounties](#child-bounties). This is why bounties are also called _parent_ bounties.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +Parent bounty proposals aim to access treasury funds once to fund multiple smaller proposals later
```suggestion
Parent bounty proposals aim to reserve a portion of treasury funds once that will be used later on.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +on without creating OpenGov referenda for each one of them. Bounties are managed by curators, where
```suggestion
They save proponents the time needed to create and obtain approval for several OpenGov referenda. Bounties are managed by curators, where
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +usually a curator is a [multi-signature account](./learn-account-multisig.md). Bounties can access a
```suggestion
the curator is usually a [multi-signature account](./learn-account-multisig.md). Bounties can access a
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +When submitting the value of the bounty, the proposer includes a fee paid to curators willing to
```suggestion
When submitting the value of the bounty, the proposer can specify a fee that will be paid to curators willing to
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +invest their time and expertise in the task: this amount is included in the total value of the
```suggestion
invest their time and expertise in the task: this amount will be included in the total value of the
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +bounty. In this sense, the curator's fee can be defined as subtracting the value paid to the bounty
```suggestion
bounty. In this sense, the curator's fee can be defined as the difference between the amounts paid to child bounty
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +rewardee from the total value of the bounty.
```suggestion
awardees and the total value of the bounty.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +Curators are selected through OpenGov referendum after the bounty proposal passes and need to add an
```suggestion
Curators are selected through OpenGov referendum after the bounty proposal passes; and they need to pay an
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +This deposit can be used to punish them if they act maliciously. However, if they are successful in
```suggestion
This deposit can be used to punish curators if they act maliciously. However, if they are successful in
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +their task of getting someone to complete the bounty work, they will receive their deposit back and
```suggestion
managing the bounty to completion, they will receive their deposit back and
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +part of the bounty reward as a fee payment for their job.
```suggestion
part of the bounty funding as a payment for their job.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +Curators are expected to have a well-balanced track record related to the issues the bounty tries to
```suggestion
Curators are expected to have a well-balanced track record in addressing the issues that the bounty wants to
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +resolve: they should be at least knowledgeable on the topics the bounty touches and show project
```suggestion
solve. At the very least, they should be very knowledgeable on the topics covered by the bounty and have proven project
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +management skills or experience. These recommendations ensure an effective use of the mechanism. A
```suggestion
management skills or experience. These recommendations help ensure an effective use of the bounty mechanism.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +Bounty is a reward for a specified body of work - or specified set of objectives - that needs to be
```suggestion
A Bounty is a reward for a specified body of work - or specified set of objectives - that needs to be
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +days with the possibility of being extended by the curator. Aiming to maintain flexibility on the
```suggestion
days, with possible extension(s) to be requested by the curator. To maintain flexibility during the
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +tasks’ curation, the curator will be able to create child bounties for more granularity and
```suggestion
tasks’ curation, the curator will also be able to create child bounties for more granularity in the allocation of funds and 
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +allocation in the next iteration of the mechanism.
```suggestion
as part of a nested iteration of the bounty mechanism.
```

2023-10-30 13:44 UTC, anaelleparity commented on docs/learn/learn-polkadot-opengov-treasury.md
> +Child bounties are spawned from [parent bounties](#parent-bounties). Child bounties access funds
```suggestion
Child bounties are spawned from [parent bounties](#parent-bounties). Child bounties are used to access funds
```

2023-10-31 10:31 UTC, filippoweb3 commented
@anaelleparity I accepted all changes from your side. Let me know if this PR is good to go :)

2023-10-31 14:15 UTC, DrW3RK approved these changes
some minor fixes enhancing readability.

2023-10-31 14:15 UTC, DrW3RK commented on docs/learn/learn-polkadot-opengov-treasury.md
> +part of the bounty funding as a payment for their job.
```suggestion
part of the bounty funding as a payment for their efforts.
```

2023-10-31 14:15 UTC, DrW3RK commented on docs/learn/learn-polkadot-opengov-treasury.md
> +Curators are expected to have a well-balanced track record in addressing the issues that the bounty wants to
```suggestion
Curators are expected to have a decent track record in addressing the issues that the bounty wants to
```

2023-10-31 14:15 UTC, DrW3RK commented on docs/learn/learn-polkadot-opengov-treasury.md
> +management skills or experience. These recommendations help ensure an effective use of the bounty mechanism.
```suggestion
solve. They should be very knowledgeable on the topics covered by the bounty and have proven project
management skills or experience. These recommendations help ensure an effective use of the bounty mechanism.
```

2023-10-31 14:15 UTC, DrW3RK commented on docs/learn/learn-polkadot-opengov-treasury.md
> +executed for a predefined treasury amount to be paid out. The responsibility of assigning a payout
```suggestion
executed for a predefined treasury amount that is designated to be paid out. The responsibility of assigning a payout
```

2023-10-31 14:15 UTC, DrW3RK commented on docs/learn/learn-polkadot-opengov-treasury.md
> +organizers needing to pay costs upfront or close to the event's date. Bounties solve this problem by
```suggestion
referendum, can be a long and uncertain process. This is not always a suitable option, for example, for event
organizers who need to pay costs upfront or close to the event's date. Bounties solve this problem by
```

2023-10-31 14:15 UTC, DrW3RK commented on docs/learn/learn-polkadot-opengov-treasury.md
> +allowing access to treasury funds once to fund multiple events later on through
```suggestion
procuring access to treasury funds in a single shot and use them to fund multiple events later on through
```

2023-11-03 11:13 UTC, merged