Update learn-hyperbridge.md
w3f/polkadot-wiki pull request #5507
Opened 2024-01-14 02:32 UTC by chungquantin

Submit Hyperbridge docs

2024-01-15 13:05 UTC, filippoweb3 requested changes
Thank you for this great contribution to the Wiki! I added some feedback.

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +To fully follow the material on this page, it is recommended to be familiar with the concepts of the [Parachain](https://wiki.polkadot.network/docs/learn-parachains) and [Bridges](./learn-bridges.md)
```suggestion
To fully follow the material on this page, it is recommended to be familiar with the concepts of [Parachain](./learn-parachains) and [Bridges](./learn-bridges.md).
```

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +Interoperability is the core vision of the Polkadot technology. Through years of blockchain development, there has been many effort into making a secure interoperability solution to communicate betwe
```suggestion
Interoperability is the core vision of the {{ polkadot: Polkadot :polkadot }}{{ kusama: Kusama :kusama }} technology. Through years of blockchain development, much effort has been put into making a secure interoperability solution between blockchains.
```

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +With that vision in mind, Hyperbridge (short for hyper-scalable bridge) is innovated as a cross-chain solution built as an interoperability coprocessor. Hyperbridge is crafted to scale cryptographica
```suggestion
Hyperbridge (short for hyper-scalable bridge) is innovated as a cross-chain solution built as an interoperability coprocessor. Hyperbridge is crafted to scale cryptographically secure, consensus, and state-proof-based interoperability across all blockchains.
```

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +Expanding more about the coprocessor model, it has been applied in other solutions of offloading cryptographic computation as well, particularly, **SNARK coprocessor model**.
any link to SNARK coprocessor model?

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +- **PLONK verifier**
link?

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +- The Barretenberg backend
link? Or brief explanation?

2024-01-15 13:05 UTC, filippoweb3 commented on docs/learn/learn-hyperbridge.md
> +Interoperable State Machine Protocol (ISMP) provides a familiar HTTP-like API for developers who want to make cross-chain requests to trigger certain logic on the counterparty chain. It allows making
Link to ISMP?

2024-01-15 13:08 UTC, chungquantin commented
@filippoweb3 thanks for your feedback. I'll will make changes based on it

2024-01-18 10:07 UTC, filippoweb3 commented
@chungquantin there are still some links missing. After that I am happy to approve and the PR.

2024-01-18 16:56 UTC, chungquantin commented
@filippoweb3 I have added links to resolve your feedback. Please take a look and let me know if there are anything else to update.

2024-01-19 10:52 UTC, filippoweb3 approved these changes
thank you! I will create a separate PR to do some minor edits and add you as a reviewer :)

2024-01-19 10:52 UTC, merged