Update and rename builders-program.md to alpha-program.md
w3f/polkadot-wiki pull request #5652
Opened 2024-03-04 10:39 UTC by joshuacheong

Changed the Substrate Builders Program and Square One into the updated Polkadot Alpha Program (Please see the blog post for more context: https://polkadot.network/blog/the-polkadot-alpha-program-a-new-era-for-decentralized-building-collaboration/)

2024-03-04 18:38 UTC, CrackTheCode016 requested changes
looks mostly good to me, except we need to make sure we replace the sidebar item as well (in both polkadot-wiki and kusama).  this can be found in `polkadot-wiki/sidebars.js` and `kusama-guide/sidebars.js`

`"general/builders-program",` -> `"general/alpha-program"`,

2024-03-04 18:38 UTC, CrackTheCode016 commented on docs/general/alpha-program.md
> +Over 150 projects are using [Polkadot SDK known as Substrate](https://substrate.io) to create the next generation of
```suggestion
Over 150 projects are using the [Polkadot SDK (also known as Substrate)](https://substrate.io) to create the next generation of
```

2024-03-06 12:34 UTC, NM2146 commented
Hey @filippoweb3 Would it be possible to merge and make these changes as SBP & Square One no longer exist. Thanks :)

2024-03-06 15:03 UTC, CrackTheCode016 commented
@NM2146 Hey, sorry for the delay!  I was waiting on @joshuacheong to add the page to the sidebars file to ensure the wiki doesn't crash, as the page for SBP is deleted in this PR. Otherwise, it's good to merge.

 If this is too much trouble, I can insert it myself, let me know!

2024-03-06 15:07 UTC, filippoweb3 commented
@NM2146 I will need to add redirects as well. This can be done on a second PR. Let me merge this and do the changes in another PR. Need also to check for broken links.

2024-03-06 15:09 UTC, filippoweb3 approved these changes

2024-03-06 15:09 UTC, merged

2024-03-07 10:48 UTC, NM2146 commented
Thanks @filippoweb3 ! Will check for other links and create a new PR for re-directs :)

2024-03-07 13:20 UTC, filippoweb3 commented
@NM2146 no need we already did it yesterday. All good ;)