Fix ipfs gateway domain.
w3f/polkadot-wiki pull request #5698
Opened 2024-03-18 19:11 UTC by AyumuKasuga

Hello my friends,
Domain `ipfs.io` does not work anymore, let's replace it to by another gateway --`dweb.link` which also belongs to Protocol Labs.

2024-03-19 08:21 UTC, filippoweb3 requested changes
Thank you! I added the official link -> https://cloudflare-ipfs.com/ipns/dotapps.io

2024-03-19 08:21 UTC, filippoweb3 commented on docs/build/build-tools-index.md
> +  endpoints. [Access via IPFS](https://dweb.link/ipns/dotapps.io)
```suggestion
  endpoints. [Access via IPFS](https://cloudflare-ipfs.com/ipns/dotapps.io/)
```

2024-03-19 08:21 UTC, filippoweb3 commented on docs/general/faq.md
> +[Polkadot Apps Targets tab](https://dweb.link/ipns/polkadot.dotapps.io/#/staking/targets). The value
```suggestion
[Polkadot Apps Targets tab](https://cloudflare-ipfs.com/ipns/dotapps.io/#/staking/targets). The value
```

2024-03-19 08:21 UTC, filippoweb3 commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +[Society page](https://dweb.link/ipns/kusama.dotapps.io/#/society).
```suggestion
[Society page](https://cloudflare-ipfs.com/ipns/dotapps.io/#/society).
```

2024-03-19 08:21 UTC, filippoweb3 commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +[Society page](https://dweb.link/ipns/kusama.dotapps.io/#/society) under the bids section. You can
```suggestion
[Society page](https://cloudflare-ipfs.com/ipns/dotapps.io/#/society) under the bids section. You can
```

2024-03-19 17:28 UTC, AyumuKasuga commented on docs/build/build-tools-index.md
> +  endpoints. [Access via IPFS](https://dweb.link/ipns/dotapps.io)
Changed

2024-03-19 17:28 UTC, AyumuKasuga commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +[Society page](https://dweb.link/ipns/kusama.dotapps.io/#/society).
Changed

2024-03-19 17:29 UTC, AyumuKasuga commented on docs/general/faq.md
> +[Polkadot Apps Targets tab](https://dweb.link/ipns/polkadot.dotapps.io/#/staking/targets). The value
Changed

2024-03-19 17:29 UTC, AyumuKasuga commented on docs/maintain/kusama/maintain-guides-society-kusama.md
> +[Society page](https://dweb.link/ipns/kusama.dotapps.io/#/society) under the bids section. You can
Changed

2024-03-20 08:07 UTC, filippoweb3 approved these changes

2024-03-20 08:07 UTC, merged