Workflow to build and host Parachain Implementer's Guide
w3f/polkadot-wiki pull request #584
Opened 2020-06-17 16:57 UTC by lamafab

Hi

This PR contains:

* Github Actions workflow to automatically build the Parachain Implementer's Guide every hour (and only commit if something changed). The workflow runs for about 30 seconds. The output (live version) is saved in `website/static/implementers-guide/`.
* Link in the sidebar:
![image](https://user-images.githubusercontent.com/42901763/84926385-9867a380-b0cb-11ea-80b3-8e7f3fe8b6f0.png)
* A page in the `docs/` directory. I tried to link the live version directly, but Docusaurus [currently does not support it](https://github.com/facebook/docusaurus/issues/827).
![image](https://user-images.githubusercontent.com/42901763/84926425-aae1dd00-b0cb-11ea-9030-80441a2e84a0.png)

2020-06-17 18:31 UTC, Swader requested changes
If a direct link in the sidebar would be better for UX, it's fairly easy to hack around with some JS which is already running custom stuff anyway.

2020-06-17 18:31 UTC, Swader commented on docs/learn-implementers-guide.md
> +[**The live version**](/implementers-guide/) is build from the source located in the official
```suggestion
[**The live version**](/implementers-guide/) is built from the source located in the official
```

2020-06-17 18:57 UTC, lsaether requested changes
Would be better to place the link under the Build header in the sidebar (instead of the Learn section).

Is it best to place the built files in the repository? Maybe what we can do is just deploy every time a new version is built so we can avoid committing the built files to this repository?

2020-06-17 19:55 UTC, lamafab commented
@Swader 

> If a direct link in the sidebar would be better for UX, it's fairly easy to hack around with some JS which is already running custom stuff anyway.

If you can quickly do that, then why not. But maybe it's useful to keep it the way it is, since it also links to the source (there's not "Edit" button in the guide). Second opinions?

@lsaether 

> Would be better to place the link under the Build header in the sidebar (instead of the Learn section).

The Implementer's Guide is more for people who want to (re-)implement the Polkadot Node (Soramitsu, ChainSafe and probably for some Parity devs themselves), not necessarily for the devs who just want to **use** Polkadot. So "Learn" is the right place. Or maybe even link it under "Parachains" (in the "Resources" section, https://wiki.polkadot.network/docs/en/learn-parachains#resources)?


> Is it best to place the built files in the repository? Maybe what we can do is just deploy every time a new version is built so we can avoid committing the built files to this repository?

You're much more familiar with the design structure of the wiki, you tell me how this should be done :)

2020-06-18 06:33 UTC, laboon commented
> Would be better to place the link under the Build header in the sidebar (instead of the Learn section).

I think it might be better under Learn since the vast majority of developers on Polkadot won't need to ever deal with this directly, but it is technically about Building.

2020-06-18 12:09 UTC, lsaether approved these changes
Looks good. At some point in the future we should move the build action to correspond with deployment to avoid having to commit the static files directly to the source, but that's an enhancement that can come later.

2020-06-18 12:17 UTC, lamafab commented
> Looks good. At some point in the future we should move the build action to correspond with deployment to avoid having to commit the static files directly to the source, but that's an enhancement that can come later.

Once the Implementer's Guide is considered "stable" it will move in its own repository anyway (discussed with Rob). For now that's okay.

2020-06-19 04:38 UTC, Swader approved these changes

2020-06-19 04:39 UTC, merged