Community PR - Dune Dashboard (2a)
w3f/polkadot-wiki pull request #5976
Opened 2024-06-19 21:48 UTC by mkchungs

# Community PR - Dune Dashboard Phase2a

This is the followup PR of #5933, where we have included another 20+ parachains & dashboards from Dune Integration Order Form 2.

**Documentation Previews**

![Onboarding-Status-Key-Dashboards-·-Polkadot-Wiki](https://github.com/w3f/polkadot-wiki/assets/17832330/beba0874-edfa-44c5-91d8-99a554674c5e)

![Polkadot-Ecosystem-Overview-·-Polkadot-Wiki](https://github.com/w3f/polkadot-wiki/assets/17832330/c2acc354-b2bc-40a1-8ae5-8b2198c5c860)

2024-06-20 11:15 UTC, filippoweb3 requested changes
Thanks for this contribution! Main points for the review:
- Page description must be as short as possible
- you'll -> you will, no abbreviations
- If there are no useful queries (most of the time it seems), consider removing that section
- Avoid "check back later" as this implies you will need to keep updated that part anytime soon

Feel free to shorten descriptions even further, as it seems the same info is present in the Overview section of each page.

Hope this helps! :)

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/polkadot-dashboards/polkadot-dashboards-governance.md
> +  An comprehensive data analysis of Polkadot governance systems, including treasury management,
```suggestion
  A comprehensive data analysis of Polkadot governance systems, including treasury management,
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/snowbridge-dashboards.md
> +will be updated with materialized queries for Snowbridge.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/astar-dashboards.md
> +  earn rewards by creating decentralized applications.
```suggestion
  Astar Network is a blockchain platform designed for
  Web3. It is compatible with both EVM (Ethereum Virtual Machine) and WebAssembly, enabling seamless
  interaction between the two environments.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/astar-dashboards.md
> +earn rewards by creating decentralized applications.
```suggestion
Astar Network, previously known as Plasm, is a blockchain platform designed for Web3.
It is compatible with both EVM (Ethereum Virtual Machine) and WebAssembly, enabling seamless
interaction between the two environments. Developers can participate in the Build2Earn program to
earn rewards by creating decentralized applications.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/astar-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/bridgehub-dashboards.md
> +  Kusama.
```suggestion
description: Polkadot BridgeHub is a system parachain within the Polkadot ecosystem, designed to
  enable trustless bridging between Polkadot and other blockchains such as Kusama and Ethereum.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/bridgehub-dashboards.md
> +will be updated with materialized queries for BridgeHub.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/centrifuge-dashboards.md
> +Some assets are managed on Ethereum, others are managed on Centrifuge (a polkadot parachain.)
```suggestion
Some assets are managed on Ethereum, others are managed on Centrifuge.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/collectives-dashboards.md
> +  off-chain through the Polkadot Fellows repository.
```suggestion
description:
  The Technical Fellowship is a self-governing body of experts and developers of Polkadot and Kusama
  networks protocols.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/collectives-dashboards.md
> +# Manta Dashboards
```suggestion
# Collectives Dashboards
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/collectives-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Manta parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Collectives parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/collectives-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/energywebx-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/frequency-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Frequency parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Frequency parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/frequency-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/invarch-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Acala parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Acala parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/invarch-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/litentry-dashboards.md
> +  applications include airdrop whitelisting, credit scoring, and cross-platform reputation building.
```suggestion
description:
  Litentry is a decentralized identity aggregator that links user identities while ensuring privacy
  protection.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/litentry-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Litentry parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Litentry parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/litentry-dashboards.md
> +will be updated with materialized queries for Litentry.
```suggestion
Currently, there are no specific queries provided. 
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/manta-dashboards.md
> +  ecosystem projects, offers user-friendly access to powerful ZK-enabled use cases.
```suggestion
  Manta Atlantic is a fast and decentralized ZK Layer 1 supporting modular on-chain
  compliance identities.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/manta-dashboards.md
> +ecosystem projects, offers user-friendly access to powerful ZK-enabled use cases.
```suggestion
Manta Atlantic is a fast and decentralized ZK Layer 1 supporting modular on-chain
compliance identities. Its suite of core products and technologies, including zkNFTs, staking, and
ecosystem projects, offers user-friendly access to powerful ZK-enabled use cases.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/manta-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Manta parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Manta parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/manta-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/neuroweb-dashboards.md
> +  governance vote on OTP in December 2023.
```suggestion
  NeuroWeb is a decentralized AI blockchain that rewards knowledge creation and sharing.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/neuroweb-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Neuroweb parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Neuroweb parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/neuroweb-dashboards.md
> +will be updated with materialized queries for Neuroweb.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/nodle-dashboards.md
> +  efficiency.
```suggestion
  Nodle is a parachain on Polkadot focused on providing connectivity and data liquidity for the
  Internet of Things (IoT).
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/nodle-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Nodle parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Nodle parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/nodle-dashboards.md
> +Currently, no specific queries have been provided. Please check back later for updates.
```suggestion
Currently, no specific queries have been provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/pendulum-dashboards.md
> +  open financial applications and connects them with the traditional financial sector.
```suggestion
  Pendulum focuses on bridging fiat currencies and decentralized
  finance (DeFi).
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/pendulum-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Pendulum parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Pendulum parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/people-dashboards.md
> +  enabling users to manage their digital identity and engage in community governance.
```suggestion
  People's Chain focuses on decentralized identity and social interactions,
  enabling users to manage their digital identity and engage in community governance.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/people-dashboards.md
> +enabling users to manage their digital identity and engage in community governance.
```suggestion
People's Chain focuses on decentralized identity and social interactions,
enabling users to manage their digital identity and engage in community governance.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/people-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the People parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the People parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/phala-dashboards.md
> +  protection framework. It allows for the processing of sensitive data with guaranteed privacy.
```suggestion
  Phala provides a privacy-preserving computation and data
  protection framework. 
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/phala-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Phala parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Phala parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/phala-dashboards.md
> +Currently, no specific queries have been provided. Please check back later for updates.
```suggestion
Currently, no specific queries have been provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/polimec-dashboards.md
> +  stakeholder incentives are aligned both during and after the fundraising process.
```suggestion
  Polimec offers a decentralized, transparent, and compliant method for fundraising.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/polimec-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Moonbeam parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Moonbeam parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/polimec-dashboards.md
> +will be updated with materialized queries for Neuroweb.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/polkadex-dashboards.md
> +  trustless custody.
```suggestion
  Polkadex is a decentralized exchange that combines the benefits of
  centralized and decentralized exchanges, offering a high-performance trading experience with
  trustless custody.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/polkadex-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Polkadex parachain:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Polkadex parachain:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/polkadex-dashboards.md
> +Currently, there are no specific queries provided. Please check back later for updates.
```suggestion
Currently, there are no specific queries provided.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/snowbridge-dashboards.md
> +
```suggestion
description: Snowbridge is a general-purpose, trustless, and decentralized bridge that connects
  Polkadot and Ethereum.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/parachain-dashboards/snowbridge-dashboards.md
> +Here you'll find a variety of dashboards that help visualize data from the Snowbridge protocol:
```suggestion
Here you will find a variety of dashboards that help visualize data from the Snowbridge protocol:
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/polkadot-ecosystem-overview.md
> +description: High level metrics for Polkadot Ecosystem.
```suggestion
description: High-level metrics for Polkadot Ecosystem.
```

2024-06-20 11:15 UTC, filippoweb3 commented on docs/general/dune-analytics/project-dashboards.md
> +  dashboards are created using Dune Analytics and DuneSQL.
```suggestion
  A list of dashboards about some of the interesting projects in the Polkadot ecosystem.
```

2024-06-20 13:26 UTC, mkchungs commented
Thanks for your feedback! We will improve the documentation and get back to you early next week!

2024-06-23 22:36 UTC, mkchungs commented
@filippoweb3, we have incorporated the changes based on your feedback. We have also systematically added a few more useful queries (along with descriptions) for every parachain we cover. Hopefully, users will find these queries insightful and start building more awesome queries with the granular data on Dune.

Please take a look with the latest edit and let us know what else we can improve. Thanks

2024-06-24 07:54 UTC, filippoweb3 approved these changes
thank you for implementing the changes and adding more stuff. Nice to see some data on the Wiki :)

2024-06-24 07:55 UTC, merged