Wiki Reorg: Funding Section
w3f/polkadot-wiki pull request #6137
Opened 2024-08-08 10:10 UTC by filippoweb3

2024-08-08 16:39 UTC, CrackTheCode016 reviewed
It overall looks fine to me, I do not have as many insights into the grants program and the like, so ultimately will wait for @semuelle to give the go-ahead on the details to do with funding.

2024-08-08 16:39 UTC, CrackTheCode016 commented on docs/general/funding.md
> +Check out the [programs](programs-index) for all kinds of ecosystem support opportunities.
```suggestion
Check out the [programs](programs-index) for numerous ecosystem support opportunities.
```

2024-08-08 16:39 UTC, CrackTheCode016 commented on docs/general/funding.md
> +If you are certain you want to apply for a W3F grant, head straight to our
```suggestion
If you are certain you want to apply for a W3F grant, head straight to the
```

2024-08-08 16:39 UTC, CrackTheCode016 commented on docs/general/funding.md
> +_Will the grant be awarded to those delivering a complete product that everyone in the ecosystem can
Maybe these would be better as a numbered list, or similar?

2024-08-27 09:02 UTC, filippoweb3 commented
@semuelle can we merge this one?

2024-08-27 09:25 UTC, semuelle commented
@PieWol Can you look into this?

2024-08-28 10:50 UTC, PieWol commented
Hey @filippoweb3 ,
sorry for the delay. I'd like to come up with a new funding flowchart as we no longer accept any DF application. Hence it doesn't make sense to show this as a current funding source. I'll get back to you shortly.

2024-09-17 09:00 UTC, filippoweb3 commented
@PieWol any update?

2024-09-17 10:13 UTC, PieWol requested changes
just some minor changes with decentralized futures being removed from the chart.

2024-09-17 10:13 UTC, PieWol commented on docs/general/funding.md
> +    B -->|Existing POC| E[Treasury or Decentralized Futures]
```suggestion
    B -->|Existing POC| E[Treasury]
```

2024-09-17 10:13 UTC, PieWol commented on docs/general/funding.md
> +```
```suggestion
    style C stroke:#e83e8c,stroke-width:2px,stroke-dasharray: 5 5
    style E stroke:#e83e8c,stroke-width:2px,stroke-dasharray: 5 5
    style F stroke:#e83e8c,stroke-width:2px,stroke-dasharray: 5 5
    style H stroke:#e83e8c,stroke-width:2px,stroke-dasharray: 5 5
    style J stroke:#e83e8c,stroke-width:2px,stroke-dasharray: 5 5

    click C "https://grants.web3.foundation/docs/Process/how-to-apply" "Apply now"
    click F "https://grants.web3.foundation/docs/Process/how-to-apply" "Apply now"
    click H "https://wiki.polkadot.network/docs/en/learn-polkadot-opengov-treasury" "https://wiki.polkadot.network/docs/en/learn-polkadot-opengov-treasury" _blank
```
```

2024-09-17 10:13 UTC, PieWol commented on docs/general/funding.md
> +    D -->|Yes|J[Decentralized Futures]
```suggestion
    D -->|Yes|J[Venture Capital]
```

2024-09-17 12:01 UTC, merged