Add section on multisig deposits
w3f/polkadot-wiki pull request #635
Opened 2020-06-30 15:49 UTC by lsaether

2020-07-02 10:03 UTC, Swader requested changes
We should clarify where the deposit is coming from: should the multisig itself have the money to cover the deposit, or is it the initiating signatory?

2020-07-02 10:03 UTC, Swader commented on docs/learn-accounts.md
> +also approve the call. When Bob come to approve the call and execute the transaction, he will not
```suggestion
also approve the call. When Bob comes to approve the call and execute the transaction, he will not
```

2020-07-10 10:56 UTC, Swader reviewed
If the script is the same as in your msig-utils script, something's off, it doesn't give the same address as the Polkadot JS Apps UI. Recommend fixing first.

2020-07-10 16:00 UTC, lsaether commented
msig-util has been fixed and the code example points to that repository now. The original example had a bug in how it sorted the addresses before hashing.

2020-07-11 17:40 UTC, merged