Update learn-treasury.md
w3f/polkadot-wiki pull request #744
Opened 2020-07-31 12:26 UTC by rrtti

Add bounty spending mechanism information as the third treasury spending mechanism.

2020-07-31 12:48 UTC, Swader commented
Remember to run prettier to make CI pass. `npx run prettier --save` should do I think.

2020-08-11 01:47 UTC, lsaether commented
@rrtti Is this ready for review?

2020-08-11 08:09 UTC, Swader commented
I think we're waiting for implementation to finish so we can test drive on a dev chain and get screenshots for the guide

2020-10-15 10:41 UTC, rrtti reviewed
Ready for review.

2020-10-15 11:24 UTC, Swader requested changes
Nitpicks

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +Bounties Spending proposals aim to delegate the curation activity of spending proposals to experts called Curators: They can be defined as addresses with agency over a portion of the treasury with th
```suggestion
Bounties Spending proposals aim to delegate the curation activity of spending proposals to experts called Curators: They can be defined as addresses with agency over a portion of the treasury with the goal of fixing a bug, vulnerability, develop a strategy, or monitoring a set of tasks related to a specific topic: all for the benefit of the Polkadot ecosystem. 
```

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +A proposer can submit a bounty proposal for the Council to pass, with a curator to be defined after whose background and expertise is such that they are capable of determining when the task is comple
```suggestion
A proposer can submit a bounty proposal for the Council to pass, with a curator to be defined later, whose background and expertise is such that they are capable of determining when the task is complete. Curators are selected by the Council after the bounty proposal passes, and need to add an upfront payment to take the position. This deposit can be used to punish them if they act maliciously. But if they are successful in their task of getting someone to complete the bounty work, they will receive their deposit back and part of the bounty reward.
```

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +Anyone can create a Bounty proposal using Polkadot JS Apps: From the website, use the Extrinsics tab and select the Treasury pallet, then `Propose_bounty` and enter the value and description of the p
Unfinished sentence at the end?

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +A bounty can be cancelled by deleting the earmark for a specific treasury amount of be closed if the tasks have been completed. On the opposite side, the 90 days life of a bounty can be extended by a
```suggestion
A bounty can be cancelled by deleting the earmark for a specific treasury amount or be closed if the tasks have been completed. On the opposite side, the 90 days life of a bounty can be extended by amending the expiry block number of the bounty to stay active. 
```

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +The curator can close the bounty once it approves the completion of its tasks. The curator should make sure to set up the payout address on the active bounty beforehand. Closing the Active bounty ena
```suggestion
The curator can close the bounty once they approve the completion of its tasks. The curator should make sure to set up the payout address on the active bounty beforehand. Closing the Active bounty enacts a delayed payout to the payout address and a payout of the curator fee.
```

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +A bounty can be closed by using the extrinsics tab and selecting the Treasury pallet, then `Award_bounty`, making sure the right bounty is to be closed and finally sign the transaction. It is importa
```suggestion
A bounty can be closed by using the extrinsics tab and selecting the Treasury pallet, then `Award_bounty`, making sure the right bounty is to be closed and finally sign the transaction. It is important to note that those who received a reward after the bounty is completed, must claim the specific amount of the payout from the payout address, by calling `Claim_bounty` after the curator closed the allocation. 
```

2020-10-15 11:24 UTC, Swader commented on docs/learn-treasury.md
> +To understand more about Bounties and how this new mechanism works, visit [Polkadot Blog](https://polkadot.network/kusama-and-polkadot-now-reward-curators-helping-to-scale-councils-functions-join-the
```suggestion
To understand more about Bounties and how this new mechanism works, read this [Polkadot Blog post](https://polkadot.network/kusama-and-polkadot-now-reward-curators-helping-to-scale-councils-functions-join-the-force-moving-the-community-forward/). 
```

2020-12-02 15:49 UTC, laboon commented
What is the status of this?  @rrtti

2020-12-02 16:15 UTC, rrtti commented
@laboon I have edited the content in the last committed version for users to understand they need help from a council member until the UI is ready. Once the UI Bounty is closed we will have screenshots of where the user goes to submit one on Polkadot.js Apps, for now i have edited the content for a temporary use (see "### Creating a Bounty Proposal"). 

Let me know if that works, we wont have a screenshot for a few weeks at least.

2020-12-03 10:51 UTC, laboon commented
@rrtti So is it ready for re-review?  It's still listed as draft.

2020-12-10 13:14 UTC, laboon requested changes

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +There are practical limits to Council Members curation capabilities when it comes to treasury proposals: Council members likely do not have the expertise to make a proper assessment of the activities
```suggestion
There are practical limits to Council Members curation capabilities when it comes to Treasury proposals: Council members likely do not have the expertise to make a proper assessment of the activities described in all proposals. Even if individual Councillors have that expertise, it is highly unlikely that a majority of members are capable in such diverse topics.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +Bounties Spending proposals aim to delegate the curation activity of spending proposals to experts called Curators: They can be defined as addresses with agency over a portion of the treasury with th
```suggestion
Bounties spending proposals aim to delegate the curation activity of spending proposals to experts called Curators. Curators are defined as addresses with agency over a portion of the treasury with the goal of fixing a bug, vulnerability, develop a strategy, or monitoring a set of tasks related to a specific topic for the benefit of the Polkadot ecosystem. 
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +A proposer can submit a bounty proposal for the Council to pass, with a curator to be defined later, whose background and expertise is such that they are capable of determining when the task is compl
```suggestion
A proposer can submit a bounty proposal for the Council to pass, with a curator to be defined later, whose background and expertise is such that they are capable of determining when the task is complete. Curators are selected by the Council after the bounty proposal passes, and need to add an upfront deposit to take the position. This deposit can be revoked if the curator is found to have acted maliciously.  If they are successful in their task of getting someone to complete the bounty work, they will receive their deposit back as well as the bounty reward.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +When submitting the value of the bounty, the proposer includes a reward for curators willing to invest their time and expertise in the task: this amount is included in the total value of the bounty.
```suggestion
When submitting the value of the bounty, the proposer includes a reward for curators willing to invest their time and expertise in the task. This amount is included in the total value of the bounty. The curator's fee can thus be defined as the result of subtracting the value paid to the bounty rewardee from the total value of the bounty.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +In general terms, curators are expected to have a well-balanced track record related to the issues the bounty tries to resolve: they should be at least knowledgeable on the topics the bounty touches,
```suggestion
In general terms, curators are expected to have a well-balanced track record related to the issue the bounty tries to resolve. They should be knowledgeable on the topics the bounty touches, and ideally also show project management skills or experience. A Bounty Spending is a reward for a specified body of work - or specified set of objectives - that needs to be executed for a predefined Treasury amount to be paid out. The responsibility of assigning a payout address once the specified set of objectives is completed is delegated to the curator.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +After the Council has activated a bounty, it delegates the work that requires expertise to the curator who gets to close the active bounty. Closing the active bounty enacts a delayed payout to the pa
```suggestion
After the Council has activated a bounty, it delegates the work that requires expertise to the curator who gets to close the active bounty. Closing the active bounty enacts a delayed payout to the payout address and a payout of the curator fee. The delay phase allows the Council to act if any issues arise immediately after payment.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +To minimize storage on chain in the same way as any proposal, bounties don't contain contextual information. When a user submits a bounty spending proposal, they will probably need to find an off-cha
```suggestion
To minimize storage on chain in the same way as any proposal, bounties don't contain contextual information. When a user submits a bounty spending proposal, they will probably need to find an off-chain way to explain the proposal (any of the [available community forums](community) serve this purpose). [This template](https://docs.google.com/document/d/1-IBz_owspV5OcvezWXpksWDQReWowschD0TFuaVKKcU/edit?usp=sharing) can help as a checklist of all needed information for the Council to make an informed decision.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +To minimize storage on chain in the same way as any proposal, bounties don't contain contextual information. When a user submits a bounty spending proposal, they will probably need to find an off-cha
Ideally we'd move the template to IPFS or some other more permanent way to access it but it's not necessary.

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +The bounty has a predetermined duration of 90 days with the possibility of being extended by the curator. Aiming to maintain flexibility on the tasks’ curation, the curator will be able to create sub
```suggestion
The bounty has a default duration of 90 days with the possibility of being extended by the curator. In the future, the curator will be able to create sub-bounties for more granularity and fine-grained allocation.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +Anyone can create a Bounty proposal using Polkadot JS Apps: Users will be able to submit a proposal on the dedicated Bounty section under Governance. The development of a robust user interface to vie
```suggestion
Soon, anyone will be able to create a Bounty proposal using Polkadot-JS. Users will be able to submit a proposal on the dedicated [Bounty](https://polkadot.js.org/apps/#/bounties) page. Currently, this page can only be used to view active bounties. The development of a more interactive user interface to both view and manage bounties in Polkadot-JS is currently being worked on, itself as a bounty. For now, the help of a Councillor is needed to open a bounty proposal as a motion on which to be voted. 
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +A bounty can be cancelled by deleting the earmark for a specific treasury amount or be closed if the tasks have been completed. On the opposite side, the 90 days life of a bounty can be extended by a
```suggestion
A bounty can be cancelled by deleting the earmark for a specific treasury amount, or closed if the task has been completed. The period for a bounty to be completed can also be extended by amending the expiry block number of the bounty to a higher block number. 
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +The curator can close the bounty once they approve the completion of its tasks. The curator should make sure to set up the payout address on the active bounty beforehand. Closing the Active bounty en
```suggestion
The curator can close the bounty once they approve the completion of all of the associated tasks. The curator should be sure to set up the payout address on the active bounty beforehand. Closing an active bounty enacts a delayed payout to the payout address as well as the payout of the curator fee.
```

2020-12-10 13:14 UTC, laboon commented on docs/learn-treasury.md
> +A bounty can be closed by using the extrinsics tab and selecting the Treasury pallet, then `Award_bounty`, making sure the right bounty is to be closed and finally sign the transaction. It is importa
```suggestion
A bounty can be closed by using the [extrinsics](https://polkadot.js.org/apps/#/extrinsics) page and selecting `treasury.awardBounty`, setting the correct bounty ID and beneficiary, and then submitting and signing the extrinsic. The account that received a reward after the bounty is completed must claim the payout themself, by calling `treasury.claimBounty` after the curator has awarded the bounty. 
```

2020-12-10 13:17 UTC, laboon commented
Raul - I made some wording changes, please do this and double-check formatting and links.

I vote we get this in now and I can add screenshots later.

2020-12-10 15:25 UTC, rrtti commented
@laboon: Sounds good, all resolved - if you want to add a screenshot already for it to be there the first iteration of a UI is on Apps ready for users to see.

2020-12-10 15:25 UTC, rrtti reviewed
All good from my PoV.

2020-12-10 15:31 UTC, rrtti commented on docs/learn-treasury.md
> +To minimize storage on chain in the same way as any proposal, bounties don't contain contextual information. When a user submits a bounty spending proposal, they will probably need to find an off-cha
do we need to add a link here for the community forums?

2020-12-10 16:30 UTC, laboon commented
Merged in these changes as PR #1431

2020-12-10 16:30 UTC, closed without merging