Remove links page, place links in their desired pages
w3f/polkadot-wiki pull request #803
Opened 2020-08-18 08:56 UTC by krichard410

This PR covers the second point from #768 

Specifically, 
Remove learn-relevant-links or merge with another document. It does get some traffic, but is largely orphaned. We should consider moving the links like the 4 papers from the getting started page into this page, and then linking to it from the getting started page, i.e. "Polkadot has published four different papers, each for a specific audience. They're listed and described in the Polkadot Papers section of our Relevant Links page."

Note, that I've left out Substrate and Kusama links as I think they should be placed on their separate sites.

2020-08-18 11:54 UTC, Swader requested changes
You comitted the polkadot-wiki file, please `git rm` it. This happens because when you're testing the PDF on your local branch, it will get pulled into new branches you create if you don't clear it, and since it's only in gitignore in the pdf branch it is not getting auto ignored.

2020-08-18 11:54 UTC, Swader commented on docs/getting-started.md
> +  - [Polkadot & Substrate Overview](https://www.youtube.com/watch?v=0IoUZdDi5Is&feature=youtu.be) -
```suggestion
- [Polkadot & Substrate Overview](https://www.youtube.com/watch?v=0IoUZdDi5Is&feature=youtu.be) -
```

2020-08-18 11:54 UTC, Swader commented on docs/learn-governance.md
> +  - [Governance on Polkadot](https://www.crowdcast.io/e/governance-on-polkadot--) - An explanation
```suggestion
- [Governance on Polkadot](https://www.crowdcast.io/e/governance-on-polkadot--) - An explanation
```

2020-08-18 11:54 UTC, Swader commented on docs/learn-polkadot-host.md
> +  - [ChainSafe's Go PH](https://github.com/ChainSafeSystems/go-pre) is a 25-person development team
```suggestion
- [ChainSafe's Go PH](https://github.com/ChainSafeSystems/go-pre) is a 25-person development team
```

2020-08-18 14:06 UTC, Swader commented
I'm afraid this might infect our history with the binary file. @lsaether do you know if merging this would pollute history with 30MB extra? Should @krichard410 re-submit the PR from scratch without this file?

2020-08-18 18:11 UTC, lsaether commented
That's a good question, I assume we're only polluting GitHub's git server and not the user's git client unless the user checks out the commit that included the file.

2020-08-19 07:47 UTC, laboon commented
It will pollute the git history with the binary file so we should get rid of it.

Solution is to rebase against master and squash all commits - this will remove any superfluous files.

```
git checkout master
git pull
git checkout -
git rebase -i master
# change all commits except the top to start with "s" (for squash)
git push
```

Let me know if you have any issues!

2020-08-19 07:59 UTC, laboon commented
I just did it myself - I initially forgot that you had to force-push (although that's not quite as worrisome on a branch as master)

Should be good to go with no binary in any commit

2020-08-19 08:38 UTC, Swader commented
Thanks Bill!

2020-08-19 08:38 UTC, merged