Created a small section on Polkadot 2
w3f/polkadot-wiki pull request #816
Opened 2020-08-24 10:17 UTC by krichard410

Closes #285 
This PR includes a very small and (a bit) vague paragraph on Polkadot 2.0

2020-08-24 11:06 UTC, Swader approved these changes
I would try to find out more info and be at least a bit more verbose on this.

2020-08-24 11:06 UTC, Swader commented on docs/learn-launch.md
> +After the 1.0 version of Polkadot is released, research for the next version of Polkadot will
Version 1.0 is _technically_ released, and 2.0 research is _technically_ underway. I don't think this section adds much value as it tbh.

2020-08-24 11:07 UTC, Swader requested changes
Meant to set it to request changes

2020-08-24 15:24 UTC, lsaether commented
I think we could go more into detail on the feature set of Polkadot 1.0. For 2.0, we can just give a list of planned research directions since we don't really have much more detail than that yet. I know for example, Jeff wants to include a VDF into the protocol at some point which would definitely not be something that gets in before the 1.0 release is cut. 

If we follow the release tags we're still on 0.8 minor releases.

2020-09-11 14:30 UTC, Swader requested changes

2020-09-11 14:30 UTC, Swader commented on docs/learn-launch.md
> +- Nested or heirarchical Relay Chains, where Relay Chains could be connected through parachains.
```suggestion
- Nested or hierarchical Relay Chains, where Relay Chains could be connected through parachains.
```

2020-09-11 14:30 UTC, Swader commented on docs/learn-launch.md
> +- Nested or heirarchical Relay Chains, where Relay Chains could be connected through parachains.
I don't think it's accurate to say Relay Chains could be connected through parachains. A nested relay chain would *be* a parachain, so a *relay parachain*.

2020-09-11 14:30 UTC, Swader commented on docs/learn-launch.md
> +- Support for three tiers of parachains, each working in parallel to one another.
Can you clarify this? I don't think I understand, and I haven't heard of this concept before

2020-09-28 11:24 UTC, FatemeShirazi approved these changes

2020-09-28 11:26 UTC, Swader requested changes

2020-09-28 11:26 UTC, Swader commented on docs/learn-launch.md
> +- Nested Relay Chain: How can multiple Relay Chain's exist connected through parachains? How many
```suggestion
- Nested Relay Chain: How can multiple Relay Chains exist connected through parachains? How many
```

2020-09-28 11:26 UTC, Swader commented on docs/learn-launch.md
> +  various Relay Chains? How is XCMP working in the nested setup? How is AnV going to work there?
Maybe add links to XCMP and AnV docs in wiki.

2020-09-28 11:33 UTC, merged