Reference new DOT in FAQ
w3f/polkadot-wiki pull request #867
Opened 2020-09-01 09:17 UTC by krichard410

Closes #829

2020-09-01 14:06 UTC, laboon requested changes

2020-09-01 14:06 UTC, laboon commented on docs/faq.md
> +August, 2020, Demoniation Day, the DOT (old) value was redominated to 1e10 Plancks, meaning that the
```suggestion
August, 2020, Denomiation Day, the DOT (old) value was redenominated to 1e10 (10'000'000'000, or ten billion) Plancks, meaning that the
```

2020-09-01 14:06 UTC, laboon commented on docs/faq.md
> +new DOT was valued at ten decimal places. Following the redomination, the new DOT changed back to
```suggestion
new DOT was valued at ten decimal places. Following the redenomination, the new DOT changed back to
```

2020-09-01 14:06 UTC, laboon commented on docs/faq.md
> +DOT.
It didn't "change back" to DOT, we started _calling_ it DOT instead of _New DOT_.

2020-09-01 14:06 UTC, laboon commented on docs/faq.md
> +DOT.
Include link to the Redenomination page here.

2020-09-01 14:41 UTC, laboon commented
Kirsten -
   Looks better but just realized that there are a few other places where new DOT are referenced.  We should call all DOT just "DOT" (_not_ New DOT) except on the redenomination page, FAQ, or anywhere else we are specifically referring to the redenomination.

```
(1094) ~/web3/polkadot-wiki/docs $ grep -i "New Dot" *.md
build-protocol-info.md:redenomination occurs, we recommend that you use the symbol "_New DOT_" to clearly indicate that you
build-protocol-info.md:> redenomination from its original sale. New DOT are 100x smaller than DOT (old). Therefore, your
build-protocol-info.md:example, when a user claims their DOT from the Ethereum DOT indicator contract to a new DOT address,
learn-DOT.md:(also known as _New DOT_) are equal to 1e10 Planck.
learn-accounts.md:(on Kusama) or 0.01 DOT (old) / 1 _New DOT_ (on Polkadot mainnet) .
```

2020-09-01 14:41 UTC, laboon commented
@krichard410 ^

2020-09-01 14:55 UTC, krichard410 commented
@laboon I changed the "learn-dot" and the "learn-accounts" pages, the "build-protocol-info" page had the three new DOT reference to the redenomination.

2020-09-02 06:57 UTC, laboon requested changes

2020-09-02 06:57 UTC, laboon commented on docs/learn-DOT.md
> +(also known as _DOT_) are equal to 1e10 Planck.
```suggestion
are equal to 1e10 Planck.
```

2020-09-02 06:57 UTC, laboon commented on docs/learn-DOT.md
> +(also known as _DOT_) are equal to 1e10 Planck.
Doesn't make sense to say DOT (also known as _DOT_) =)

2020-09-02 06:57 UTC, laboon commented on docs/learn-accounts.md
> +(on Kusama) or 0.01 DOT (old) / 1 _DOT_ (on Polkadot mainnet) .
```suggestion
(on Kusama) or 1 _DOT_ (on Polkadot mainnet) .
```

2020-09-03 08:04 UTC, merged