Updated Auctions page
w3f/polkadot-wiki pull request #949
Opened 2020-09-14 10:18 UTC by krichard410

Closes #918

2020-09-14 10:59 UTC, Swader requested changes

2020-09-14 10:59 UTC, Swader commented on docs/learn-auction.md
> +> case, you don't pay DOT for a parachain slot.
I don't understand this - "In this case you don't pay DOT for a parachain slot"? Do you mean "In this way, you pay for the parachain slot by forfeiting the profit opportunity from staking the bonded tokens."

2020-09-14 11:46 UTC, joepetrowski commented on docs/learn-auction.md
> +> tokens.
```suggestion
> way, you pay for the parachain slot by forfeiting the opportunity to earn staking rewards.
```

2020-09-14 11:57 UTC, joepetrowski approved these changes
I think this change is good as in the page is definitely better with it. But to close #918 I'd like to see even more introductory material. As in, before even the "Mechanics of a Candle Auction" section, something should explain what a parachain slot is (what is being auctioned) and this information regarding tokens being reserved and returned later (what do parachains bid _with_).

As the page is now, diving right into candle auction mechanics without any context makes the page less useful.

2020-09-16 09:25 UTC, laboon commented
Yeah, we need to add even more information on parachains, but let's just get this info for now.  I've added an issue here - https://github.com/w3f/polkadot-wiki/issues/970 - for more general information.

2020-09-16 09:26 UTC, merged